apiVersion: v1
kind: Secret
metadata:
    name: volsync-immich-library
    namespace: immich
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bs4mC1YlIzd8qo7ElxtH5SS1mEGRq7kcgU4w2tG7p4vqTHJUyqIn6NIT/kgaqM9TkZ4+u8c/IgA=,iv:PCBWEjc7gf4b+By0pBxZf3zUMqgKZlXziMAU783vB0Y=,tag:3HfbdUg41+j9ACEVIYQ9qw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VzMUwI46Vw2YId6Vp+LU6Bs98yWXLK0fdxUlAZURlB2+Scb0wgGUfw==,iv:PoTAf8sSho7YfOWob/wj+4O8CItAYWLIto0j6I21gE4=,tag:5J9j7VDXVDf2o0QIfYhuxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mpg2UvXeMw==,iv:2jizw2twNF/1/r0M8Q67ATg4s/0n+Vm2NZq+IkiWiXA=,tag:a3hDKdIvkPrlusDLzL5wGw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zwWiOOEcZ/Qce+ELmy4gyjEVBMJR8qLbAb01RarNfqLk1xnJskLWeg==,iv:ef+FuizHXwvzq7GqZfeD8380RPgerI9a9srgOxotpJI=,tag:2tsoLtcCzjNaRLR3nr+Bpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHVmNVk0L3pXalFKSjJL
            OCtXUDNQRzY2KzVHdStpQnArcGw1Q2NnWTNrCmI5cDdqZlFHbElyQ0wwQWlUbEVK
            WGRaWmcwTldubU1CZVplVGFCS0ZSdG8KLS0tIGpyV25YdVlSckhJcThvWTNZSWRG
            ditXYjZMVUZ5cUlXUHZLYThlOHRveVEK2nTjyGRkrOwxrxJ4Rr2aGAisjCa9OKJE
            yVj4kebvFsG82hW7nH1bc89jp/fhMbhHAeQq/90ts6lWi7Artq2uuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T11:24:50Z"
    mac: ENC[AES256_GCM,data:u6VCBAHrlPzez+PS8vAgqQfcy6JNjOMH6ioPfNi/FAOJxDKjXFuKSQk2eJJ9EUR4+7+747FITYv1XW0Gk9PfWNmUk5jKxCm83e9Azh2GdXcy9nudhSHsSQRRlaHKFGNhz3Cbu7EHl4Rr28RoWByyvTrrJlsQwItCaTmaJmju9Jg=,iv:isrM9mMCNFe+EhbXD22j6cnavWK0KhHgOqb0FyKlTN0=,tag:sn1nY5+IQ5rx9kPyf67ZzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
