apiVersion: v1
kind: Secret
metadata:
    name: volsync-immich-library
    namespace: immich
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:tpeKyPFHEMOOIbb0NRCKJByvBPrCMQ1d0D1QNmDXRWLaTBHvUczJzl6qudCetIBZdAAl/rTL6YXZOqsVNLjlJVGMGFNem1Y7Aqi/9A==,iv:ODFtddxQEcdfbHcomMoD9PUS7rfVCNVVftwcEn5ROXA=,tag:DFNyhGFor64CFQS7fC/a5g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VzMUwI46Vw2YId6Vp+LU6Bs98yWXLK0fdxUlAZURlB2+Scb0wgGUfw==,iv:PoTAf8sSho7YfOWob/wj+4O8CItAYWLIto0j6I21gE4=,tag:5J9j7VDXVDf2o0QIfYhuxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mpg2UvXeMw==,iv:2jizw2twNF/1/r0M8Q67ATg4s/0n+Vm2NZq+IkiWiXA=,tag:a3hDKdIvkPrlusDLzL5wGw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zwWiOOEcZ/Qce+ELmy4gyjEVBMJR8qLbAb01RarNfqLk1xnJskLWeg==,iv:ef+FuizHXwvzq7GqZfeD8380RPgerI9a9srgOxotpJI=,tag:2tsoLtcCzjNaRLR3nr+Bpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHVmNVk0L3pXalFKSjJL
            OCtXUDNQRzY2KzVHdStpQnArcGw1Q2NnWTNrCmI5cDdqZlFHbElyQ0wwQWlUbEVK
            WGRaWmcwTldubU1CZVplVGFCS0ZSdG8KLS0tIGpyV25YdVlSckhJcThvWTNZSWRG
            ditXYjZMVUZ5cUlXUHZLYThlOHRveVEK2nTjyGRkrOwxrxJ4Rr2aGAisjCa9OKJE
            yVj4kebvFsG82hW7nH1bc89jp/fhMbhHAeQq/90ts6lWi7Artq2uuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T02:15:10Z"
    mac: ENC[AES256_GCM,data:1fLS8BFCuYdwSRbSPdE7bB9bz0twbtevxu7TU4ewSHgfwezdhs4Atrwfb0CNh3XaLazpd7Ci9q7TuMB6ZEXGvIIDjc5U4oZvMLmElDCgBWnv9jGdZ6XHkkCjeEUHxhmLXYU6UI5Eh/UQXWroQnyMV8122CpbqtyzLP5pmTu6kmU=,iv:2GZ56fLyCZ2c5qFdaptvX/Vyq5tsKT4RHNm8qS7MVMA=,tag:iVlk01O9dXU4skfyAhIzKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
