apiVersion: v1
kind: Secret
metadata:
    name: crunchy-pgo-vector-secret
    namespace: database
stringData:
    encryption.conf: ENC[AES256_GCM,data:CnO1G422HFRTftW8Vo2EpB5jKdEln0iVftaxzQaUpAFrcgIT0E4tag==,iv:N8nTAto+ov9UvQf6O6qzMhUD0IK+k7s/+AACaiA1yKg=,tag:agzFJgqZXjqYeXYdoI5tjA==,type:str]
    s3.conf: ENC[AES256_GCM,data:2Cpa3h05hIJAqKqj7R/GxUBTs3co+eukvExLb+pgZnT8SD0Epf6ZRQ==,iv:HPFUBj5idtfHY4xGdXgxy7QNBkEQPLUn2cwAjxbf8ys=,tag:BGXA1P0a6lBCRS8KszOGPA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOTUxZlF0bHpaMlE5T2hy
            WVkwR2JnRmpIeEpvcENMenc0cDRGR08xRzI4Ck0wdVJReWtSWENkMjhIa3E1cC9k
            aC9uZGhVUXhPalFsUmV4RUNpbmd2bWsKLS0tIDRaRktOVk9jZ0YzWklpK0hPNy9p
            eCtRNVVIa3hiZHFlWkxnTFRJRDZteTQKg8SBUAIqKSM8cPUZ1bteczd5KekX9eSC
            RI2HmaUmT/6fXnlvLgQcFEAMU0Cx8mB65z9w8Ctw28kDtCQBsZIJDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:41Z"
    mac: ENC[AES256_GCM,data:yUcof4GbCWN0UeI6s79hOKUHssDwhfMn6x/I6xWIU7ynEvqBUfV+RGupVv+rJuRqkLyGjcT4ckSEvCyBVzcujtF1zdXTkGb6kbKngO0PwqcV1QweNlGns7FXSuFd1DlY1EBbsTsMMKFpzJETemJD/AkFp1DdMyQE8jJBUfCt2Fs=,iv:29+fV3aaYmFo2DD5Gew1/a6FEQj/Xp0z44zsokqawug=,tag:3hhHLF96N0GV1qZqyov2Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
