---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-forgejo
  namespace: forgejo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.4-0
  postgresVersion: 16

  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gsks1
        resources:
          requests:
            storage: 5Gi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              storageClassName: gsks1
              resources:
                requests:
                  storage: 5Gi

  users:
    - name: forgejo
      databases:
        - forgejo
      options: "SUPERUSER"

  databaseInitSQL:
    name: forgejo-init-sql
    key: init.sql
