# ENCRYPT THIS FILE with: sops -e -i frigate-secret.sops.yaml
# Before encrypting, fill in real values for all fields marked <CHANGE_ME>
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: frigate
type: Opaque
stringData:
    #ENC[AES256_GCM,data:r3zSadQrVhADoBDJcglnNljTlu9Z3IcPlWjivxMYa6/tp/IbexFsn6MJBO+fQBCJFQzw2SudoCVfAEonqkgbRcVJ48CSkQ2imqiz,iv:7PtZHEsR5rl5KrgNQPzz/MEULCaMMG5yJyDjjstTI+s=,tag:3TuUksMIsIESt6HvDsofpA==,type:comment]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:wEB6V8yZk0wjCw==,iv:QOjj2IgPgHuQ4ZHISAIoqCNJari6uyNOj+LZMK4Qnjk=,tag:LWd28dQAaRqsGdb9Nb3shQ==,type:str]
    #ENC[AES256_GCM,data:4t4bTKFqonu61icbHb+4REIaKON2YofbSdkuBQnWb7HRGQ2i/O8DUuat+bW85gRs/GZcfG8LhsHqs1u7s+DGCKba7VaAPurfbM5u20dpH6A=,iv:v5pJzC9FBipYAz5bonYf2VMkwaIA2h1HJjXrRCJ5QtE=,tag:O7m1Wj1IbUH8vGuZBwB6cw==,type:comment]
    FRIGATE_BARNSOUTH_USER: ENC[AES256_GCM,data:+2WAZAFJ7Su7yPBqbHLm,iv:i560LCK9wP2gVz3uuv7XYQO+8f8v0swDrCAMn2Kg1Ew=,tag:M6GpXIf7VSkEvUA5/28rcA==,type:str]
    FRIGATE_BARNNORTH_USER: ENC[AES256_GCM,data:PH3Af3q7U5MKnnNbImaF,iv:7WsmIuWWwmpN4zn8J5JvTNMXJwvNCtCYdOVhD5H8mSU=,tag:PbYK5wv+y2VnbQmVwxPK9A==,type:str]
    FRIGATE_BACKDOOR_USER: ENC[AES256_GCM,data:3wibfAxu,iv:JBT6jJta+WPn4ikv/owQqqs4k0bbkLWt8v3O4x7+TAc=,tag:Rcj/G8k26zHHqguVNAaMJA==,type:str]
    FRIGATE_BARNCHARMER_USER: ENC[AES256_GCM,data:2rwjDbZm,iv:jomdpxFIFBotxnv3G2oYD0wccFrmd1koKhfhTHjRLDY=,tag:DZ7m21DXDbSbiTiNFzvR/Q==,type:str]
    #ENC[AES256_GCM,data:tBVbCi9m+GokWTTm5Xataac06Q+0jtk+nie+riR8,iv:HuRqvV3x9v8IgbU1AHAVbL2KppL9rrEN7WNz7Fm9sxw=,tag:Zm3zGpCMufbkEiIb6Z+gSA==,type:comment]
    FRIGATE_ADMIN_PASSWORD: ENC[AES256_GCM,data:Da/YsLLL0lCobMK9LARQ/ldkbVw9a4JTVAvYsLdkopa8KSCS4n1SKA==,iv:PeV+X9phP1dM1Z3ioeiz8AGo27Qi49/ERCsxSBj5nfw=,tag:GvW0Ewp3yAr1PNk62Z5FOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWmdpODIrSU44NnpYOWxz
            WmZVK2sxeTJmSzVlMmJIZEFUSnpXeGNiN3pRCi9mS2JjTnNRUXl0UUI2YWNPNXJE
            aUFaN0ZicG9GUy9nNVdUWnl2ZTc4eFUKLS0tIEtEbWJ0QTVWdjkwQ0xNWWFDZGxV
            QW5lK0ZKVjdGeFRNTEZrMUVSZlh6cHcKLKV7wAeC4/viCYJ70KayBDKL+anjdnD8
            wPtLtyH//7O9SqlmIlOYSWqP1jZ1oReVbEE+Ww0uR+Aw8x7YptywwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T23:12:03Z"
    mac: ENC[AES256_GCM,data:ApXh47EBgwY/ZJuUXqaT41aNsAvAxb9gNq43Ng93AOFlmcd5/xCYAauvOQem1/ePB/LQDGvS7o5eo6B7yYDCOQwTysi3aF07atJNgM+HRI0n4RQVk2AWAvKtfTdv9eTYigjOdXptBk6pYRMJHyNpQD/iRFHVjy7yTzpZ25Idpks=,iv:JMKiNDZRTs+1n9F3JbRgNdAlD2ALKa6fXGknujwxV68=,tag:rhKwB0LrqC8Fmf2nKpv3UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
