---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate-external
  namespace: frigate
  annotations:
    external-dns.alpha.kubernetes.io/target: external.gs-farm.net
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: external
  rules:
    - host: frigate.gs-farm.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 8971
  tls:
    - hosts:
        - frigate.gs-farm.net
      secretName: frigate-tls
