---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-db-prometheus-kube-prometheus-stack-0
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gsks0
  resources:
    requests:
      storage: 10Gi
