apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fZPpF1rEbDLjnlbXNMqiOpmjI8mtNRU18GDQjJ9zTwm05y56lSIw,iv:mj+qe6OXGAI56e6rCEyTr+HVatHJIWQvdMIjp9UWd4k=,tag:ILczouUm7yB6P3iRBtyfyw==,type:comment]
    #ENC[AES256_GCM,data:+9nn2THbJA9iut8ureKSYhJ8aejbaQoC9Yoz1btI+XjJwlrRHoIWioY01xLcV4mC+QkwJqqHqg==,iv:GrEGy5YtW4T8qkBIIAId0KkpqxzfoTy5oH2BXQDeclU=,tag:gsvQwpwh8w+iC5YUEpPniw==,type:comment]
    #ENC[AES256_GCM,data:IoW4IUM0IwC+WIM9sEHEf8WEIjt4FaXekJXjnLOUGR6RMWFJQjg/HE4UNv6YRrhuXv4oU3IpmubzRWqZJl+Lf5QCl+c=,iv:tTRVnV13SGB6LXxYwDtlCE5JYmiUkt0ccx5m8DD/a2w=,tag:6vWJfwgP1fb9YQu3RIbSMw==,type:comment]
    #ENC[AES256_GCM,data:iGjJZDAyrUt/DTsO9ut4T5UPyH9dUdw2fp0aS15c4oY=,iv:oTdzwnfJqhDsrIcGoJ6KT2Jaa0ABbopMaUu+qssIW+U=,tag:jcDu1Gi6ORlyO0l6fBCS6Q==,type:comment]
    password: ENC[AES256_GCM,data:6DEZWlZh3cEQNwCpo4iPOA==,iv:uAYXZ2AQWVxLNwOL5TBwdxAL0gBUGILEyGjwKtCcYRQ=,tag:PYAZ4crhRGHA3qjF71FRwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0xOb0RiV1d5RzNkMW1u
            VURxQ2k2L1BEUXF5Y0srSi9FTlRmcy82T1hFClZVY0wwa3hsekVMVjE3Yi9wL1BE
            YUR5QlVSMmRMY1hCQVBodHh3Q1JQK1EKLS0tIFZMNFZQQzNKYm9XamFCRnZhTlpi
            Smc1Yk10OW9ibmpRcURpSERDSzVjNGsKwyZo9h4eEH4TaAXYZmtfRqid3571fp6G
            Crr6QBbMLXUhhSWQYSdUrNhJ+LF44suEMGkgwd0FZ9LAhXMb+GdV7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T01:02:09Z"
    mac: ENC[AES256_GCM,data:QoWBy3PE4ygqE3msm7IGwtnfkL0YJqr6i/Z03Rpr056OezRdqbnhG5XlR/heT9WdLDSkoQZTe00W218qFAOWAwi7TVXvhTp1gUyqu0oiqtaHocT2y/kb2u33VZdLH4mV3sOeOojzE50sIA9TBTuhhXYE3YN+oZZn5YmrxAZ714c=,iv:tswJ8/Gm9f/fqM4tenS2LH8zgiTbBFVwNdUks30o6As=,tag:xiMPfDiUf3sLSi7oi6ThKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
