---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./certificate.yaml
  - ./pvc.yaml
  - ./volsync-secret.sops.yaml
  - ./volsync.yaml
