---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
