apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    minio-root-password: ENC[AES256_GCM,data:TXVDW4DRxVAwNJiRm/7LLTUQ+o6RE1BhIypjXWVY8XpQ6HHei5Uagg==,iv:B/p3iu9pgN/prlSjc1Xv+hmXTAaP1t1f5DWuE1iPo8I=,tag:CSH7N1WzFJ3PXh3X3RevZw==,type:str]
    minio-root-user: ENC[AES256_GCM,data:DWQHmfAc1Q==,iv:a6SnHI7yKmof3x0WHRozPWbfDoxczoWh4WDPqnKOLSU=,tag:zfyRPf7UWa5ZC0CLepyetA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOW9YTFk1VitnQXo0VUNH
            THpndG1iSlhKOGRwcUFvQXNqNHVaemNMRFEwCmVxNjZBZXNhbWp4WGw2byt6VkNq
            YmNlZE9GUkNmTUhPaUlaWm40Q0RLNncKLS0tIFpUNk55UlV6ckdKc25uaWhiV0xu
            T0oyUE10Y1ZsTGhROC9TOUpoOSsxNGcKNjEEYroBZL6J+4owUqWNtr3juLWqps3b
            K2hdMWMrY7gS96z+w67YBrOtFSuv7qNsrcgW0G/7o1ECK7B44EZoRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:31Z"
    mac: ENC[AES256_GCM,data:HOUXuVj/E9ho52XgiAQb0G/RNHg2vGcW3EPGqjRQmf59/DARb2oepf/WWeyY/fDxIx1sl1gRLtrP0n3xQd7bsATNWVehsC9r2SvFUkofu4OjEX/bDTH+KMvoeXQFNkdqK1L3PD/HtWR3v4/JJTyfm0SKzE02dyZzbZoMaIJDURM=,iv:/No5v25QPnBFzrPi2MrQg3p4yAhgKGm8hR9RjdctOqE=,tag:9FqyYQdHyc5vMjGuMwJY+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
