apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    minio-root-password: ENC[AES256_GCM,data:9EYVzYBUXLm4ufKayEqo0UfU2rxyTDudjJ6DL8VAEXrt8ORsIRU6hg==,iv:CZyHP6JqypSfEKMhLzJTMToNHh/0Tc/fE3r36tyntB0=,tag:y/LAXqzQ63uJcLaLjlpzSQ==,type:str]
    minio-root-user: ENC[AES256_GCM,data:0HnPMe9g7Q==,iv:++vmtgUVBySoxV6O8UB5dg7FzqzNLhTVsQKvigiKVdM=,tag:2A7UrKOfQLO6rYp3iLgLKA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaVVGYURYODg1a1NieWtU
            cUVHQnlUWHFsUWpRczJHVXBCWHV3eWsvblFrCkFrNS9hU01oOGQwcW4zUGFQbVZB
            NmgyRysrVHAvUnJscmpqVmtPTm1zVk0KLS0tIHhNYzJ5Rm1YL0hkekVSNnRPMk5Y
            RUw2RnFscno4UUphRzlnbWd4Z3FpcXMKJyA2fSSnVnH8u/3kIimDY0DJ6oN+hNhX
            2T0qCQEMK63xk1Sv5uO/clTjLYHzwIvXl08uMPry/EH7PJeUSTGOZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:09:36Z"
    mac: ENC[AES256_GCM,data:M2WNPurGs7sPWBAIXe9+bdBadW88m1STETyE61dlrZxwx/6V8HG+1VRFSzhGmdafQh2QDaDrIKm/Y3vcoCwdEUgQIxgdOQRoR7Su6pqvNSzFXTAVwr+jwssW06M21oyBZJJLmgc55Z1mXTKEHPl0o4xXKaX+NUs12ZSzDKKouPo=,iv:/b3PwF6xrCG2DQeofvCtWA3j65OgtTRgNyZXpJTPkwo=,tag:7u0y7VTF5/GNgRvDtstVww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
