apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    minio-root-password: ENC[AES256_GCM,data:bVQ0tmji5JlYTWyU9Ibq1rMyb9eFx8F5vmUJRM/EOKGktY0XSCguJA==,iv:HCm8wiGyQmSXPqVUCmK7humSubfDNWOai4JkQIDwRkA=,tag:zuH2yWdGupLFXNvzDzUCag==,type:str]
    minio-root-user: ENC[AES256_GCM,data:9b9SAxQK6Q==,iv:jsQZ0e9V8aT+SDRWgBHY5oi0TNpIpUv+qrpNcQn0+Lk=,tag:VZFS/THNlVgBna6/QX1gfw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TWJuZjBDNlFwY2FtWE16
            OWZtbnhWZDBNbzBqc1IycUlnTHNiVFJXUHlrCnV5SmduWXRvY1JyTG9VTmRsQVhQ
            SjVMRldDM1kwQ2djQnJqV0pTcFpVMm8KLS0tIDF2Wnk5bFNUZVVHOHFLRzFxRi9I
            QWdHSURidlFyK2VJUVhSY0h6cHY1ejgKxtZ8El2UmkkuYcOnSh38S4ctbdob83VV
            PMl/3mvCVBcn6oPpE26ZMATIjrd2XyodOZBp0/FvDPjOvuQLn09eZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:36Z"
    mac: ENC[AES256_GCM,data:VwwAM2YwjtTXaBLhEfjaO2lUt4gQtQhdn+pNwyxjVj+RwvFx/PTHS8d61biepq/E581upbwLgkEbMBXB7MXc/pFBi5+IWuQtzYHoPFNjrCVy0OlPWPVTlcn7sd/TN1oNS6FMRJfM/Kd4etV1BTX3pmJk5MAKlDtmtt9QHP+DhWY=,iv:rdFY3twpeFUWsW/UZsc47YcVbJpp6P71TklkeT75X64=,tag:UmayTKn3O2+lOda4O+c5qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
