apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-nfs
    namespace: minio
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:v/ifHaZKQZhkQKi/DcGDKUCznFRbQUEhwfKw19Wmf+ScMhtrvJ6VGn37PWCKiEb3+3uT,iv:qWD72Jf6XJnwx1MuFSgUSB5vQ4WwT/LuMCTdRqYatxc=,tag:pn7lBiFePdnYZGrc5LViZA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:MH6buegEE1+1aHPTy5CwMwBEg7gzs9W/WMuG7kks2nMlGrPKgSgGxA3DzaQ=,iv:b5RRpTQxRhcf+pS9MK56HoSphFhk9SbwazOXpszMzJI=,tag:PkC1tV3sxFYB+CcnaDV5mA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g+SIoC0v4Q==,iv:0tipdTM3VAoTejnC+LKUjVS5Zb6HXZVdv2W8v8/59fo=,tag:/vA33lHhDKFH+nVMpXFYAg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1NSBYle3mu0s47mk7BCv0aCWsSYJ+jC/WTpqJEHDddwK3PhjJmrQXg==,iv:fCr1h79nm8oXkTfFe3wPJJBupVSRcpN2ROCRplGVNco=,tag:VBaSHVibyAANOjVm2fSr/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOVlVRWdMOXl4ck9aTDdJ
            bm9INWd0VzE1aXBPa1NoOGl0dzQ0Tnh2eEc0CjBrWnNWdlBybTRxWnUzS0VuakxD
            S3p0UnNqYTN3Wkh0Y1lQanppTndoTncKLS0tIHRZNDZZcmhKMmFnMmR6Z3lScUNW
            aWdhWml5NWdXeTBlN3V4WmlvOEUrSHMK6G0wRtInbHg0NCD2nAOutyMbv6u+vWNW
            GtP4aEzwLDrbHSjb/8ovMFHNMlRAzE9dyGeBHrN2XxkNxsV06kNO5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T10:31:35Z"
    mac: ENC[AES256_GCM,data:AcxpUIqIxzKy7HKrILshPW361XMPEFQKFy6mYPDIcpLwsllhScDYgv9prmFT6jQp81rSJTQ259+agd7OIvDlhMloOnR+UuLocpyKIrd6G7tah+13iPdYxRTBAR+fjYVXXf07QBeehuWFogAqqUp9EipcrhEbTcLs7WYUpupk+g8=,iv:xXtyN4bhHgFRfL9BR8SoLK0LHvP8TMd6ZP7+tnxbZLM=,tag:M/CeRojeJlzh9q1dPJ4ptw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
