---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minio-nfs
  namespace: minio
spec:
  sourcePVC: minio-nfs
  trigger:
    schedule: "0 4 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: volsync-minio-nfs
    storageClassName: gsks0
    cacheStorageClassName: local-hostpath
    retain:
      daily: 7
      weekly: 4
      monthly: 3
