ansible_become_pass: ENC[AES256_GCM,data:ymzvdjVDhM2wSjJGPVl7fS4jog==,iv:VxPAeNqd4m4Y24jR1PY50mDidEgL5fWLYO2UYXQtGYg=,tag:bGmSUBs8B4/eHietXdE73Q==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYmkvdEMrWVpTU2hDa20y
            REc3cGpGems2dkJCK1R0RzBVbldQVWplRmk4CmhnVExrYnhtZ1ZUcWFWcE9Fd0hu
            djlRUng5NGd3RjJRb1M5S0l6cWNqWUEKLS0tIEFkbGJ5cGhqOXlvci8xTXJDaTlz
            R1VLelRLOXVGL2w0ZVNjWVEyQkg4cUUKryEoGtosRgUExL/i7BWTL0uhSzEGCJz9
            TKUHQpM+yJjZr9p9FXuW67j5s4vkcfLN2tVHeOvRUyQGCgDj6nrlvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:17:34Z"
    mac: ENC[AES256_GCM,data:iJotk5zKsvTCaqgpW5APtRuwJvNSVTgkW1LMiTBQBrvcWszDp+cpO0IHGpopqWbIJF0A/rPMdpipZrb825TSVMSmlDiRBzNJxfVA9QiUIFeTe2kB9oGNWyPNu97+vamSIi/G7Lkr18lC7LLyiBSt+iwQLskVNOYGLUXv27dzA00=,iv:0nyR1usjt8MXufarOMv+4a9f8I5CXCH6PWA425Xz8rg=,tag:uV4EgAOA+HBxC3Fw4tpYKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
