ansible_become_pass: ENC[AES256_GCM,data:V3aes38zKn82iLHBsKO6E9prWw==,iv:VZr2QK5f9WzNu8iu9LKl7Rlm1XfSm2VMzhRrkMwRgVc=,tag:DtUkqbxreh2KPaWPCk9QxA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMmpJeCsyRnVwYXFybmhV
            ZnlEQm5kTFE5SGovRnQ3dGVSNkRXMTdPbEZzClo4cEIyZkRCUW9YcWxRTGwzc1NR
            em1YUG9qTVBBeDQ0cVhLQmFPQnZCUjgKLS0tIHIzald4Z0JmbmQvTW9YK1hzSjRh
            d2x4VVZyOTk4bDc2ZXpzcHhQYVl0WmsKe4DC6GG2+p1zghnLLgHRetVU0Sb6TSsN
            rrgTZYrClLuEH2zaG3J3XMCjXkG8owkf3Ss2fTIydLHMV9OvudCk6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:24:08Z"
    mac: ENC[AES256_GCM,data:Z7PDN2Z2eb8csFkjONguCASiKT+GurNpO/bDcmsrwYIwC6PjhLgAdibVEASgDKFJXMdps18PRDxah00FMM7M29FLPTTLnD1WbfUEf2C4VN04sDhMZ8LYMk50WDq10iMFbKQ4iU1D+B4O9h7fOrfMSOgQyo7sUj6ObCrhcTJTvdU=,iv:9HlUkWtBnII9vZmOf2ZXLb2LWOAgJwxcoXnR9vmiJOY=,tag:2AHDSRGKtBwWSHNW0XNhTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
