ansible_become_pass: ENC[AES256_GCM,data:E06tHQ7WO/4pWtMqtZnyO0twVw==,iv:TyLg+Fzd98onqz/m24p1pdLBvcpFF9Z/b/ORSDbbqBM=,tag:87/cSSFzUzYZlCQuTqR0wg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvME00MlBoRjVSQmcwck0v
            NkZtNSsrcW4vVVl1Um9zanNEcXR3YTFmcjBnCkI4dUo4cUdFUEtXUEY0cCs4dzE2
            TU1BVHZWZUZabDhxQVpTMzZhWFQ5a1kKLS0tIFduR2RhaTRTTWpHVW81NDNZSzJv
            b2kvM09VWVFnNnVlTkJCalc3RkVSMHcKIUiD884RDR0zoHFLHGC7lsvwNWtg1f8c
            rpUR8G8QvEChzDodsCrkp42dpRFFztXPcHe5PwaoswBV9jF73ZG7rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:40:17Z"
    mac: ENC[AES256_GCM,data:J43R237RYhX2YBucb3D55zityHTKlUmnJIgOMEGQ5JRcLJsfylvDew1U93DTCYRPqaE7ynYrSk0QXW/GAyHTZ8+aWMxrGtxnKrC81xKNnto7sxhzvQBdBk5JLzWLBc+LTU7zgoxCFF6l15GVHxcUotDDouRfXymObxgc9lRyuSc=,iv:lqVaDyxQv7yv3+c0MgiuR7DW6/jkehbWAa10ho1BoLQ=,tag:8cguyr/p4PlzJBtnkApVVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
