ansible_become_pass: ENC[AES256_GCM,data:1GSiJV0/8sof2Jy5kxMcBLq42A==,iv:iNPh2nTsCqCqW4ddtO26RuppxGpXdTqblaRKcIi6dUw=,tag:RXlqC3+MVqVfoSRsCsuFpg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUDRwaklRQUFWbFFOSGxx
            L285Z3B1emEwZzN4N0VGU1ZYeC9yMUhDdnhNCnFoL0I5U0ducDZTeDRjUzFsbCtu
            RDkwdkE4WmFWY3VsZDJWVjFQdGVJMFUKLS0tIGIzNjZiL1RnVDk5SjkyT2hSSk5X
            RS9EQkJYdDVxK1lKYmV3cTlkLzFpY3cKlN0D/DDUDJSipTr2K8AkxIk8aHDKxtQk
            bbh41/em4kUPQNc0TZPVAwkgbD00F7C4HPSvlx5y+LKtBuAHGTD5MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:17:08Z"
    mac: ENC[AES256_GCM,data:93WZPrm83N4b/T4psVy0b3CN3KZURMep1J0FOWjgbs1CqQEASKqtKCPcbn/VkvDEnJgQ+kRYq9BhVJoDDTh9FxAekqyE4DaRG1ZZRhkJwJmc4nPWMKpk2X6wkBPd9aMQhlG/FrVBMQVGHBB3tX/YMjJhe8gAZwMkwHhTbgfJaVs=,iv:zF1VzPyzxVoS8fOqUfBJ3zUWRJLx64yZ9taiyeEgweM=,tag:ztKtwBCac3nF/GGO+J4ANg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
