ansible_become_pass: ENC[AES256_GCM,data:lktQI5RCaT0gbzIQjc3MHfBV0A==,iv:JXzMYgjEoQJujfKa5Dfvr1+QXk9pE9nQapGLAgs/o+A=,tag:orPOd/FLDO3Ulkp3Ql6VOA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbmxwWmlDNDhyMjB0amox
            am9zS2N2Si8zbG1IcmlUNi9HTDA2Mmh3YlQ0ClROQTlWOEppZFFHVHF6d0VGVk9F
            OXlpV2c4dlpUaWY4c3drUmNjVXlCcVEKLS0tIEFhL3RDZncveVZ5aWtZUU4reVdw
            cDBPWlc4NXNnU3FTNHJYSThGejEyd0kKTiEcZcthPPgeh2iONt151Wo+8jsYXGrC
            S7WC/C3yB7nFw2BIfE9sAwrJBoQtmQX8uwdBZ7S/BzMuzk6vlD0mxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:24:09Z"
    mac: ENC[AES256_GCM,data:AE0STQWXqT1gA+5VYHoJGs/9XQN6OwK8ZAACQBt59alZs0PJmuzP4T7Dci4nMiXYz34k5fdaGeTl62LFtqCIIWMY+hnYGDSsk3EM8+5p1KTtCFSqpKMj9j/ZsKfSvtC0XZmF+9OIkclUGIoTkI4wuxcCCr+qoNwboHyYcZTVcDE=,iv:6JkjYLiPBk/0ZupOh4GY0W1hZPcANkBYtUsI4Ujhoqw=,tag:00dpl3luWYwdbCvFwd6qKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
