apiVersion: v1
kind: Secret
metadata:
    name: crunchy-pgo-vector-secret
    namespace: database
stringData:
    encryption.conf: ENC[AES256_GCM,data:nC021e5pvk7u7VytmChrMz9Fsw1R5HaY+cGB6jQBsNRbjBYvbrK0Wg==,iv:qh03NbLt7wDGGfbJWmiWq9pmqSJv4pgRfdxZ2zM2Bzs=,tag:EXFJvgY4KSuywQdycQf44g==,type:str]
    s3.conf: ENC[AES256_GCM,data:gNdHr5cWpZEr1UbN/gDmoF4BIQayiqm1iuo42rDBhgUjmLfCYjTEdw==,iv:x3vOOM19T4Dw/79sHFhbybuksAeUCuahZvGgjoy7Roo=,tag:7UOAP/T/eDSKCziCCdDm3w==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L0RtemhZc0dSdnZvaFFh
            blQ4dXh1QVVJTnlFTnZ3NkJNcjZ4TmdJTVhzClZLd0cwS2VQTW9xKy9MVitEN0o2
            cDdUWlVpMWF5ejhmR0xMNnh4Q3llejQKLS0tIHRNTXpFdmNmWVEvRXB5Zyt0cW1X
            aDE0MmVzb2xYUXp4VFZFMDEvTThJYlUKcpZNbwlcJ2+N8cpbdnAZMDqs3iVJ9AJo
            gnc1giu2A3Fax6Rnve1ITlSsFpx/D82m7bYiMia71qY/1w+g1s0sEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:03:17Z"
    mac: ENC[AES256_GCM,data:PKZRelRNR6jGwebaPcqvflYHSz1UGgYaoxkuHhkqVkfMOHzNecUT2aU5Mz3cSt5yzhtYoHOwMm9cuN3kp57SW7xlryWm/8SlAo6qoxEjMusIA7+MFS841Tc9vZfbLwuVrsXZAWift1abrFONLkOw70KzbVKt3dkbg4yEas+TRdo=,iv:TWuO/3D+va6nYxFfHGQlmH1zSeGdpXRDmnDMlB8XMJM=,tag:UWRxcIpytxnoz/SyZdXZ8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
