---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.sops.yaml
  - ingress-internal.yaml
  - ingress-external.yaml
  - volsync-gitea-shared-storage.sops.yaml
  - volsync-postgres-forgejo-pgdata.sops.yaml
  - volsync-postgres-forgejo-repo1.sops.yaml
  - volsync.yaml
