apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oauth-secret
    namespace: forgejo
stringData:
    key: ENC[AES256_GCM,data:qBTeWHBBLw==,iv:F4uTkQh0neBJNoCv9lK+WJEK04f6xO4xCqCi1yIlkdQ=,tag:9i1wv4yQsqu0t2s/VGJd3A==,type:str]
    secret: ENC[AES256_GCM,data:5bQHIvRFu+Z067Phx9zt9YiJC3wQdWmXAQULbhFCSYU3dZiMzCAfCKUIwgRclAUwpWdXWG/VDrWiUmNxgz0CSb9KHbD82oMYuyPC44H9ZaRo16qP47w=,iv:KkfngokRxqsTzE4rv2FVXjDyL4YvT+JM8nvYAvPwN2U=,tag:Ps0a4diqe+oU34ZDjzcnog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOWF2dTRJTTVnN2lQVk1a
            RytVbi96blhJZkI1dFI4RE8xK3VKK3greVdvClA4SUxMMVpTdThRcTFVUWpOclVk
            MjFUeElEZWtOZ29oaGJWWmRPcy80VEUKLS0tIG4ya0NPSG9qRk9CeWpJZ295RFR0
            UGNDeEJWZExQcWE1UGdQNGhvUWlMZ28K/ytUIIbL256cRjqJKZwo6yWwNlkZjCq4
            0SOY3mJJTAug6xI7OKBKfLtt5u6YrB0+ZYOenrCaHII1N1LZqB6hQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T14:37:44Z"
    mac: ENC[AES256_GCM,data:PSjGknBhIfco7LFueGvDXlOLc/rv1gALL+Brav5Z0K8gagwOmvIE2xed7eUCXsdpcH4mfkErMZ2x5THoiWlRcAyU6FolABBBPgshZSIGuSD50lWxSEwaMO8aEgi6XaG6YE4IVJE+iZ9WVpyBMK40HQum12iFJsi9pRoP2u8t2Z8=,iv:ebaqfwvnRTUUhASngVxwRFIrFNjE1eeEwKNTOqKY+5A=,tag:SerYK6I7iKxf2MrQV30Rrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
