# Fill in adminPassword below, then encrypt:
#   sops --encrypt --age age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x \
#     --in-place secret.yaml
#
# IMPORTANT: Do NOT commit this file unencrypted.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:QGaB3GzLQJo=,iv:5p29A9ck0M+45Pg+4xdB4A//Y08jZl+NydOoIUAWOks=,tag:oHtuSJcj5e08JDCC2ulmJg==,type:str]
    password: ENC[AES256_GCM,data:fPLztDvBPq7oKWAxm2zYUc3C3ryIVKlX7uxzLzGPLQWdAGYxdR1e1Q==,iv:H23Cry+k+cCOVroBnDfA9VPLdjppPFkhuNLJtVN9cc4=,tag:uJAvl0nObw9tqcyt21qa4A==,type:str]
    gmailAppPassword: ENC[AES256_GCM,data:D7ZqKQX+EeM5kvNlLp1wgX2QBiAlYA==,iv:jjn/TfNk2QWTDZaqC/r4f/v8JmFfrhOHY6kCMaPX8XE=,tag:BSaWPp/LAA9LUql2IidbZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcjdXOVdTb09zSFFLWEk1
            RTlGNlpzZUJqREZmNFZ0clhxL0JORUpHdWg4CktmQUc5Zlk3RFdIcFE2QkVpemEx
            cG1tWXZIMGUrcmxzbFVMMWZ2RU9MQ0UKLS0tIG9nTXNUb0RlNk1ZUnIrLy91UDJD
            ek9vRmZIejR1MXR2VFl0RHExU3lDQm8KsLpfqcQWmxP6q/7927SGrjq0XO7tfv2W
            4XWGJ30ZbOkQj2xth1kst9nIR9MFtvH4XtLMG4r4k9Pz7FCMJfiT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T00:49:31Z"
    mac: ENC[AES256_GCM,data:60OOp+TPILC3SEzWcjH3ERr/h7DJpB0FFP6Vh99DJCChYJqLiCxqUnIkjnaedaUf5PpFO1Sd4DGq/Gyqln0Lkeg2/AqTryFjkNZpfpkwzYdKFuLSQR7EjxJY58SRlJCSXAByMT3AfkKYR/Z+5udG4dGABtw+XpCCgE7r/e4L/8Q=,iv:eoguJm/zOuFnJrZBV4TSSI1kaInwq5GtYl/tEsq04lg=,tag:UOzAn/q1niR4ih52O6M3HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
