# Fill in adminPassword below, then encrypt:
#   sops --encrypt --age age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x \
#     --in-place secret.yaml
#
# IMPORTANT: Do NOT commit this file unencrypted.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:FpWWNJCT7VVz3GPwcXXyvVFVfPu428mhchCZzqxylUwVn0XmXbbO5w==,iv:xcrn0i44nNPWz+zwoYJqbxr8/BX/ysfyUR2SaJnZ2hw=,tag:+l0UQ1Qa+/jjsjdbMN6x2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcjdXOVdTb09zSFFLWEk1
            RTlGNlpzZUJqREZmNFZ0clhxL0JORUpHdWg4CktmQUc5Zlk3RFdIcFE2QkVpemEx
            cG1tWXZIMGUrcmxzbFVMMWZ2RU9MQ0UKLS0tIG9nTXNUb0RlNk1ZUnIrLy91UDJD
            ek9vRmZIejR1MXR2VFl0RHExU3lDQm8KsLpfqcQWmxP6q/7927SGrjq0XO7tfv2W
            4XWGJ30ZbOkQj2xth1kst9nIR9MFtvH4XtLMG4r4k9Pz7FCMJfiT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T00:47:59Z"
    mac: ENC[AES256_GCM,data:mZJhD28yTOCCBDgtyT0aQYvQZOb2sZER4SZaa7CxCxOPTN1F6ybGAVurMUAN4WvNQog6dGM49Vl8M1DN2tC3MXDEPc0tj7i70xVvl+FPORgmotkkT4UJdzNYeTfg+azB++aadgt/kvfR3es4rJ/1DbmpfEm28k1uyrcviikSMPM=,iv:farIm99zLnNa5o5LqBPG1V0aN44kVRlZE/ymPnrLu1M=,tag:ZXS85APJhhRXhPk6ICacyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
