# Fill in adminPassword below, then encrypt:
#   sops --encrypt --age age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x \
#     --in-place secret.yaml
#
# IMPORTANT: Do NOT commit this file unencrypted.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:QGaB3GzLQJo=,iv:5p29A9ck0M+45Pg+4xdB4A//Y08jZl+NydOoIUAWOks=,tag:oHtuSJcj5e08JDCC2ulmJg==,type:str]
    password: ENC[AES256_GCM,data:fPLztDvBPq7oKWAxm2zYUc3C3ryIVKlX7uxzLzGPLQWdAGYxdR1e1Q==,iv:H23Cry+k+cCOVroBnDfA9VPLdjppPFkhuNLJtVN9cc4=,tag:uJAvl0nObw9tqcyt21qa4A==,type:str]
    gmailAppPassword: ENC[AES256_GCM,data:5Wh6BKhG8HZy6hYzWggU/fsuWw==,iv:CdkAU9e/1Uqh/Pe9LPmTUKuN5q8YsZDjHUzb2GdAR5A=,tag:tkrA40XYX4U6LwqKHRIsOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcjdXOVdTb09zSFFLWEk1
            RTlGNlpzZUJqREZmNFZ0clhxL0JORUpHdWg4CktmQUc5Zlk3RFdIcFE2QkVpemEx
            cG1tWXZIMGUrcmxzbFVMMWZ2RU9MQ0UKLS0tIG9nTXNUb0RlNk1ZUnIrLy91UDJD
            ek9vRmZIejR1MXR2VFl0RHExU3lDQm8KsLpfqcQWmxP6q/7927SGrjq0XO7tfv2W
            4XWGJ30ZbOkQj2xth1kst9nIR9MFtvH4XtLMG4r4k9Pz7FCMJfiT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T01:15:19Z"
    mac: ENC[AES256_GCM,data:S29nIXOCgHxIJpbsMZojD3LCAvxdRLbLogEj+JMjEip9rIlO6HAb5yjYug0CEP8xqnw7471i7QrtVwPsyBECIbiAxt4NuQug05GQT9FggFdk2pUzyi22YQSh6oyiy5wF8QifYMkjKFd1eOI+kvPIAEImROk1B7GDoJIQWhsRSNM=,iv:srZeOXqNjrFqrJPjdUEytQBlmFQS/3ayQo776ybcf10=,tag:CeKaY0u6ODJq0JPtO0th7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
