apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-secret
    namespace: forgejo
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sRokIHgQndOtmPEElgRa1IhpNZXDJ0xxsfIaKh8ojLMysdMbu3wZTHX/VqvCOMm3oQ==,iv:HP3t4uQ1YVtNg12AqYH6rADiD0DhqrXZJpZRVujV0rE=,tag:m/f6TLTWO4etQKrwprI+eA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dj3LVIMWbiAScCzjtxeg5sRrc08GQgqDwv1HjWlfEp7Dp4uEJFXHj31P66o=,iv:9OizwbrMAlKDzDfWhYjx8QC3fdofu4ZAJX6bLBlhVSs=,tag:wJqFy43xKwJga0l6AHEQaw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zSb6ViQRPQ==,iv:xkpI/RXsjJPESlTmqB4dKAgKx1g/31urxwO2wj2tskQ=,tag:VVqIQcL1aEZwPj/Mau3TQw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1tVBu0Vx51NL3VyzjrqPRO3UB6EMQPjK2WHEYEtmT4dfc0wVAYVHSQ==,iv:pps7rtOqvKI5YHv4jYC04CsEv1qLEEunoHPT6B1ZcQQ=,tag:yU9i7Ye6BA9q8wzBIu6cJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NnJLclVZbEtkcTJXVjBx
            c3g5a2xncmVjbWRqdloyT0F4bmZob0FqejNvCkd4VkxKRTNSYnhxN0RWSm5INzhQ
            RVp0YmxidUx5SWdIdkpuMTROMmE2Q3cKLS0tIE1aeWNWSHdhNVVtdHg2UGoySkZB
            Y092endOUllXNDNBTnZ2UnV0M29HR1UKu3oJ8aDH3YOiOTbz6KfOWyLlRLwsE1ER
            IkwZGRvPlWoe5vHmDHD88zaRU2eljK+EvhoLp0jTW0MxspsevjtpuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T01:45:47Z"
    mac: ENC[AES256_GCM,data:IMnYXQYMFHrAwiRzecrt/0kzQftn4A0sf02i1QRKMZiqsR1RmBY536AhUUrbxGZR2tr7nE4LcOM0z+iJuy212DdwJ4io8tWqr9shqvqEtcH/NNAtKDDfQ3JPt7Nn/oaKeNJ09dvWzHzW3fRVpSYAplo94t1+Uu5pF4YUk+RWrRs=,iv:rJieDxVGrMrZs0lflS2tTnMsj/joMMSleQTxioujXes=,tag:2wIeaym2mbFmz3jxWYexxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
