---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gitea-shared-storage
  namespace: forgejo
spec:
  sourcePVC: gitea-shared-storage
  trigger:
    schedule: "0 3 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: volsync-gitea-shared-storage
    storageClassName: gsks1
    cacheStorageClassName: local-hostpath
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: postgres-forgejo-pgdata
  namespace: forgejo
spec:
  sourcePVC: postgres-forgejo-instance1-wz59-pgdata
  trigger:
    schedule: "0 3 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: volsync-postgres-forgejo-pgdata
    storageClassName: gsks1
    cacheStorageClassName: local-hostpath
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: postgres-forgejo-repo1
  namespace: forgejo
spec:
  sourcePVC: postgres-forgejo-repo1
  trigger:
    schedule: "0 3 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: volsync-postgres-forgejo-repo1
    storageClassName: gsks1
    cacheStorageClassName: local-hostpath
    retain:
      daily: 7
      weekly: 4
      monthly: 3
