apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:OG8o9B/bpQPSXV066VNR1wwGnvbhqAg6yFLGGI0LkmVsenYI,iv:oUNg3wxPc/BRtr+wVltPGAOYr+MLdchQL37QdbeLOSc=,tag:MTxPRbnS+JZkE1cwHvrGew==,type:str]
    credentials.json: ENC[AES256_GCM,data:f7N0WFBcYm/b7CareHe1x2d2iGSvosXEKTF1wfNiv9pcmGX1nFxBHq7T92ji59uWcNfP/RA9xQTCNke51br85H1oRdCV/h+zyUKeTwSawg43WET9wN/2FTHOisYfMvwyVrra8ReEOnBIZVQfQrRYje1rp3s2/xvto/zsoctDucDcAuGAK6Vng6TVYGTJPFcwEsYFEYTliiwNCAGy6U5RTHx2XJ3GTK2KYKDdL6S7ig==,iv:SGcN1mk+J37ETUNnkJrRwJAYlZcAod2XgVjIHZVzNi0=,tag:S4/mtRqslz5Vell95wYyaQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWXNRQlp5TWZSZ0VjaVJE
            YTFTVXR6d3hRZ2YyTEpNMTBqcVd2YkcrYm1zCkcvQUgxWHZackFtY3ZFbXRLNWFM
            UFFsTWlCQk5VNCtobE9IQ01iQllGcm8KLS0tIEZ6L09TSFZBNFl3WlBjdmh1Zk5U
            SWo3eWkxNmVnZTlVMU5WOTdZMGZyMEUKgHdz6DOiDouf+utcLKSI2Sk7xHxDrrk9
            ptoUNsjg7Xm6QZlowIzw/UEVaoV+bPO8Q5gstf3r9FksgjmRS5Ar+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:19:21Z"
    mac: ENC[AES256_GCM,data:lr0MJ2Gq5mQ6ToojqMwP+TLC5l2cTclStGCcJjC6aaemizHutBkETWJib6+2m31Q/RhrKi6YLdkOy/SZqLicRw8wngkO573jYTz26MXCenxjAhocfKAxkWbsVUtuLs1zrzwmbcqxaOaQdl24nlVCcVNJ/+W1X9THduWA8YdE4fc=,iv:zUIZvT0JEWaz7xn7cEQurxV31BdBmvuJKLikYi1xKvE=,tag:rD6CHSz5vyCey2Ss8Ukw9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
