apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:85duiffdRLD4K7mShEqrLu0egBIqx4FAfeyqJUN3BtYXWtG8,iv:NFeszOLwobb5WhInQKgjno0Hcv86HJEYkANh7RcwZXY=,tag:38Kj3bGnz738tqU6dbIc4A==,type:str]
    credentials.json: ENC[AES256_GCM,data:N6STLQmWDgjMunVQYxLaFIdilIqCbQFpnrKIXsarfWTwM12z6fE8U7Up24sNyuoOPKXnM8n5qeGRLnu3S2ax43PAKn8NDZgZCJkZVjrV3A9jJ8S11kF5dpLluD03BJjkM5RIN/X3w8chM0H/eRw831DVW7bXP1alSLCjJWdhLIdM66tZdG6wY6InHqjAd59P22WGq015faYbxTmeYAYaqH8chab7jR0fkDWo16L19Q==,iv:r1IRyw7mxSq0Mzrjt9CCGN8OpTqE58Hqb3YyPN2KmLY=,tag:tcXJO9ZCad/HrjcY1SasbA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczI5OFgwNGNhTkhLRWNB
            Unkxd0grTkRUK0hFbXNvRms5UnJSMTNuRm44ClRhUmJLbWc2MVRQSGRtZ1NiTnRT
            cXlKTndBVC9Udi9zYkN6blo3U2MySk0KLS0tIDVFREtGb2R6Sm1xVVJ4MDVMUGV1
            cUsvaDhJSis0emtDMVNDMU4vMFU0MVEKX9KBKwih/lE3Yu58O6agFwCgDazSADbY
            KaSz0cSybZa2Tt6CsqdOrQv00EGOGWdPcar2PiOkieaMH084MaWA4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:02:28Z"
    mac: ENC[AES256_GCM,data:Mpxv3gGuLWIzRhruwYO3iVCERgQJ/LFcQlqrRg0BaOIkAdCCyxQhxCnLsyGsqGPslTr5ZCQlHqpNPW1RY9GE82VoRGV2zfvFJjcEl1Od0qB5MH8aFxfuwiC3EphvqAEvaDB0rHOgcLj/9ktmv1PSd3re7PPXePTi7CqQjYuhiYc=,iv:TefaL+WuemV5uJXehaxdzCk1USRIB5v+JYpzbOo5Uts=,tag:aFDHuQPwvquXc0/khVorjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
