apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:m0oP3aio9WT+umvtcRUUiGAQfNPju9pCsf8f92fmSMF34Zu2,iv:i8MUeLZ1yZMhROpRWzflB6zyK94BBho6MyXgSS/6Tl4=,tag:HW01oi4ybcTTWKE0/bxfkA==,type:str]
    credentials.json: ENC[AES256_GCM,data:FtUakqW8mINK0PHT5xSnZm078zVZevlFcGY8nzeK7kJ0nIopG7AhxZtGSlAajjDg4tn0Yr20+nH5XDh86QS6WQlmzkO+DKvDAGhBgh/xja1Yuah0rWgaKBSphdPI6kOn6PMh1Ni2er4I+wycs90VjrjQ5hMWlmTh/sCcMcFddlVcW0rBbdsSv4pCCoUezV4s7meabTubJtykAD5TCToq1FNuM/siIJ7ytGrKjNljlw==,iv:FaxCx2ik59YUF9DKDktWLdN2ByQ29kdQp2nX6G5ld5c=,tag:vswHqzbkwBB+N+Kvu/VSLA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRUVCQ0E1TWxJVk9CeGdo
            MFN3OEJnQTdpenMrQ1dMVjFXRDBib3RBV0RBCjNwZEtLQ1hEdWZ2K3lvK0FvaGZI
            NWhWWWRlU1l4R0dIUlFqY08rVVk3SlUKLS0tIFFkNGcyN1VGbEVjRkU2MzRyWFlp
            WitvbHNYUjRSZkxsV3A4Y0E4QmMxMVUKyL9si4QO2GUfyVfjONOi7/nZj7Jaj2Bi
            afUGmX5dXNqosugInKHqrGnAobe2zMSX0vYUYBjIvQG06WmgIHx6tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:25:50Z"
    mac: ENC[AES256_GCM,data:Xf9mbQ3jViJZdYplx42+bQn7QnGeP0p1mRfjHlMlt8lYFKsjTn55prUylVQhtDU2/NDBID5IyvHH/+r3nv831VNa66e2At+Mbfms5YTEE7PA1NkLwtIIf8fqVLzxx1PTrHC4gt/y7NNmf6e1fYSsj7N3uyKgiNHNJQnzYXOQvGI=,iv:QeSP4P2F+dTyiQcD3K8zaHEfYursHq9k/HKiGd+rKBM=,tag:z7bq77+tYFgnqDBTfCDdJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
