apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-secret
    namespace: database
stringData:
    encryption.conf: ENC[AES256_GCM,data:u1W4gGjgUjcaLQZNxu3TQHb9zzcZLl69pmyiOHP0YjwnzALsPKxogg==,iv:AmKq3kOh+4I9U8KkfeR22bjAQju+zjt9S9ASrNU+kw0=,tag:aPKvGZNhk8Efv8E//9vuDg==,type:str]
    s3.conf: ENC[AES256_GCM,data:WsZ2SSj8CEORqigVC0PLOKhQ2kyGI+fARx2v8Xm9fSxqLziSNB0Xug==,iv:d0InNaHRuDcoGXfQQA6USrw1o+vbRVBj4eMfR4ZRLHE=,tag:56t/ZjyDu2ZiECI/NAoPNw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b0JVKzFEUnJJb3ppR2l0
            cG5CUmY3M0pGaC82ejZibDNmZVRwZU5VT2xJCnorOWlicmVkOS9JUGNpajgrdXo2
            TmIyNlM4ZzYxNWkxZkhYeFpXVjlBelUKLS0tIHJSSFBzS1FBR0FWekxZWTJ2R3Ur
            b3dMUXU5Q21VT253SUtnUmpIM3Jodm8K+t0EHQcqFzx4L1cgNJqhTHpJgo66rmY0
            Ls902BUmBjx0f+693qHYv94cExW+z5pKakByRXHuMPlLf+jtHcRkOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:03:18Z"
    mac: ENC[AES256_GCM,data:LlAWk0kP0YdnRxp6p9P0RhxbRjP/goVMt0UnCfaPMGYqebeDLXbvbYNFA4gPxdzTclIGYjTvdoEk9FJMQVoNNtv26MBVrQXkiaYdlUxqL1je90mXnX0asMT2nJrqBO1Z8V9Mw/Uc9USCyP8NH8RSC9/R9g1n04zFBRJ+GbwZl0s=,iv:OgTGMPDnw/N3URdZad2/k9vTA/cpOE1E1gTos70ygKI=,tag:ItxAbEvrySQflf3esuMdwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
