apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zwVzbaxgVW7cx7BU20O9XZrCNgugtzs+,iv:b1YRGlDGZvlVne89+Q9OzBdOYL70uVvh7QI0M7UYE24=,tag:pd2UEq4YT0x0bX5cxdGgLg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRnlxV1pFcU5KTXF0WDlv
            MEM2Vjg1Tld4aWszbEx2TXQ3NUhJakZyRlZFCjYxWHdSTDA5WVdTc1RqZUFKNklu
            eFhyeTFnZzlXcCtKU1FjWWxUYmxQaVEKLS0tIDNLZ3RvZFZSMFZwYnZ0SWFnU0F1
            c2FiOTQ3MUlqaEN2YmlCOEZRcVpSNkEKbYsX2Fx3eQ41G5Ik/DfJXWHU5HTPDfDF
            h1Plv4rA+l4dReD+wgLZkQROSz90kg4PmkZDpPzcUj+BDiUgCtEJVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:41:59Z"
    mac: ENC[AES256_GCM,data:iYEWp7M/59l9n6PIZnDSFKfinrZUxxIHik050BXnX9ckDmz5g5CYBV7HCDC8EQ+QzAHZXV05eTCosCTlRnpatxqtwZwB3Q/a1WPlmaGxpzROG6p1MOYIgqqf9YO0G/fQtpXRPEdd6MC6YKebuzUxIcx6Qvj1VzSGxtsmAJWWS6I=,iv:ViDb6v97CYhUXF/3ppxC8noRH+V3+9RsaXG+B3NQUXo=,tag:PHujMUSrjzlBQ6JFbDGDMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
