apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:QZHF19tfwQ1WknnJFo3WzmnXjQ/6E1SG,iv:tTMMWxviQ3xG45ghiDu9ts5M2VFm93eqvKwYpOYdn8Y=,tag:IE5f/UKYfQvfBBu7HhNDPg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1NHUVJUcmRTSmM3SzU0
            aGd4T1kvcytZVmFpVlZFRTY3QVpGMHFSS1NBCjVtL2ZnOGRnRUFYbkdBUjgwdG1r
            K05oM1JFdWgrRFVoUUlwSFUrVEgvaWcKLS0tIGwxZy9TUGxKYVFzME43SHc4cXlQ
            VzdJQWx5eTBCYVRrbUlaMFZUaVNkZ3cKAvlTJWZ/8kYIqwoO5t7aEoZ7WTe4z50+
            2CqMQG7eCcKfV+c+hZ63HsPmC8Dq1YXzFmbxzx3CODsBuSiDVzCP5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:18:50Z"
    mac: ENC[AES256_GCM,data:zqMMcLolrCR77jkaz/ML0Lg1cKDNGByTDMt8r6sPUUfWmkaRRbbNSQHLy3utLF+Le2XC5ptpGP8wLLPAXbWNC8chtjl4OPp28AFROr3GDfH1iDw72nk+aXnYu2JBbyIVEJldoJJBoAGy1tYAvgKwz2wSI6as5BRwqC1FNe7Crrw=,iv:mLf8vYkQzvvtASdzM8++H/6Jrr4T74QkBiQBZNtAgiM=,tag:UVieCX3pVZtJviYyXa/p+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
