apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+QezjrFAXTdH48wMvrzxdAExBWWPDQLv,iv:cYquAWh0rikCXE+FAvXyJmgRVqvnOTlM7FJ69fo1tyY=,tag:kwfbwPlQYfPsKOWdAg6wvQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZXI4VzhGbkF5U3ZjNWV2
            SU1YUEFHeEp1bWtyK1FpaTQ4ZWlrVE03WVdvCkRQQ0FaZGhydVMxSEpycGpFd0RJ
            akJWbnlJOU5MUHlrK28wQUU2aHM4bDAKLS0tICt0d3JJZGVOeXZXWjczWWRsQjlZ
            VGVYSFFCZG9OdUFNSFQ3MjBVejJJVmsK3zmz9qRBBXSc7T5etYmjXdNe7wRoLZPY
            3j5QhpzKyOiSrbMsDJ4sBVgta9UFEwdLn6JJdp8riMS0VOH3E2/WaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:19:21Z"
    mac: ENC[AES256_GCM,data:u1/5QXcRD7Et+GrMexZnxgtO3G4cZz+Euj+ilQhtxmL/wrG59m81gS3WAEL4CT8kh2UJZLewUks13gBHARIa7vFBbC5xRbYAlG7duCWRiFgbrRM6vtANUDfzWBChSb+b0eK+GvgF+4XSlheSoR7SJLyHvMZM69rJYM5xu3P/Y8o=,iv:UyHX7vxFaoMDnLlIX06LTEObnbwS27zdZTW9L2UtGO8=,tag:1757II07Qt/Q+tOEDJnawg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
