apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:X8C1B1jIMLwBbkG0sn+Y7HaE00DJdWoRn1E51FM9SyW7UR/OzNw0AQ==,iv:hgN20gsEUfRFmavxHnVDR4YzpT3124pTHBIIpwIZZTk=,tag:ssLf9XPUNPHsGxHnYTb89A==,type:str]
    rootUser: ENC[AES256_GCM,data:6r1sYw==,iv:8ubJjkACZuenRUR97cPf2tcza6Od2v6D4ggUzBYjULk=,tag:PkSxiy3Fe2tkNOhO9IF3Yg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDZ1VUdLSGlzSFF2MXQz
            SDlCUDAxc1JzMGlRbXQ1NGpuZHMzSjNrWEhJClY3OC92NjRTVmlNOUl5V2IxZmYy
            dDg1Q21Ed3Q0L3FWTGkyT24rK2RGU1EKLS0tIEhvaDdZcXJORnVVNjZFMFg3Rm0z
            MDJ5OE5XTlNGNCtpNHE2d3JtY2hqRzgKQGpm0mNF2s9sI0RVuW25VxSYafkTSkww
            t1lyblFen9hPuyPTREeSfLL7Eov93wBzuG7gNX4m/2wIqmzY+IXonw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:26Z"
    mac: ENC[AES256_GCM,data:6qc62WB4FfYuudQX4Uih1iX2taY8YzqARyn8V1Ehdhvwjr16pcx5CU22V5Qf0TUFXw8yWli/MKVqAl1BPvodwcZ7QbD4DtMW12PsvF1CAFCv/nCpner6Gz6fBlh6NnxCQErNEaPadl5RBTyM8KvaxBo7S53pdK6fxOMuXRB0ikg=,iv:LcLZMop+5HT00TNIWPPJj6UYf/SetntBGeCgdwEEIIU=,tag:zRnMhN/DdMx6uBVkZg6/DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
