apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:hFBO6RTbVjgmbliGVIoCLiAR4jPNxpcH91Lj/G23LrxRk2nwhcUk7A==,iv:6COI3DLK+90+tcIeAr8Aq9CMBIRwNk8XGpF5Zx016EU=,tag:VSC09qxBR+VY8u10ouHlaQ==,type:str]
    rootUser: ENC[AES256_GCM,data:autxEw==,iv:Am/b6cIWrS1uDIE0F7D5/+kKTNHtmHU1RQ60LAoYmJs=,tag:wcdM9N+tDTEq3yOQsetUGw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZEJMYTREWjhuenBEYVpp
            OG5GcXlNZ0xHM1ZPaE1FTitERDI4QWJFeEdJCmowazV6Snh1L2dlTWxXM2xGaTNQ
            TkxoNXNsUDV2bXVpVFpCNWhONTdmR2sKLS0tIDFNVVo3eG9iVEFjK1ZYNktLUUJR
            NmJ1UzBFUEViZUZpaHJqbG1PblhPcm8KYLm6mmgh4gRCRCJO7A9xL0OmGTDz8eQ4
            Rekfmso9Lgl9pPMKgMQ/094rb/e+nFSIc33VCAffBBJXBSGOcM3cPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:26:29Z"
    mac: ENC[AES256_GCM,data:GBEUe6AEUtDlkEwd9lDLq49ZIMnqXZ4GxigOZ5/RczA8nQFABgkbl+4GRXRXnrUZEW01mJjkJhTKAOkEAs0A4VRJOVzvC6T8oX9TPg9QhChXpCmKhEThb16ZA3hS0qOZSoFTl2tTWGsqvSKQktKcNuGkvqB9lpSqcqrr3c+KC+Q=,iv:x9/RN6a1jg2EKmv7IRFji+zNgbmefMi2uXmDlqJPCc8=,tag:KyTKBIDrqvogMOwCzvjcyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
