apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:g0qahalSEgPafbygW527qLAxb571Io8AJwB1lh1htHBQp8+Ap9stIw==,iv:gpELna1lKztYvzLU6c7WMLtbMsZMrZAI9PsHwt2vVeg=,tag:9UQqSzDJC4J+fmzVBgKYkQ==,type:str]
    rootUser: ENC[AES256_GCM,data:H3OAdw==,iv:GkFnvFCjUukPS8sw/TAcoLFIBfFwYMRc9q2BGbXetYw=,tag:lZzumrtK+IbZDvg+7ZYm4w==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbUdjUzBqaWVKa3EzZmZT
            RHNTZS9XSHpXcXllZkpiVHQwSEhVYkNQekJrClFNVDFQVmp4Y09BWTFSMHRsUHJj
            UjdvaFFhN2NBbVBRdExaR3NWM3RsdkEKLS0tIGc1T1lrcmtVS2FZU3dEaUl0L3BK
            TWxvbUNiNWJtQTFNQlJHOXhiemh6SkkK5gp6pbDl1HJoiIPe8qQoG2A7lB91UlW9
            00nc0gOJuzeIWhsFuwqw61xMC0no6kOWdg7ltwfi+bXlEEZTopMC0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:34Z"
    mac: ENC[AES256_GCM,data:IACXCpNmI3FhGOxxXmTSqELjnZq7iBdpqAHCIQfBpWVnh449fVrX7h0iltlmw1Ii+6nIKYKbNWAMocYE8Z0l3VlC8XrQK52g+FWmH9eE9uaPW5C+uyCJY/3Jv7SMOQTOKHOH5xb1+VnwjIfw9F+f6uGK6xA+rzInF/pODBCbISc=,iv:3ISI+dMPTGPoPJjDKMKKM3X/J54xK3V+mnq2VOLY6n4=,tag:MSH28UgGaVdnVPOdQyRvdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
