apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
stringData:
    client-secret: ENC[AES256_GCM,data:2hMhpBfk34E74xrOC9vI4Zu/i43Qk2TAEbMUMXMTS0/hG6rAWwBRhA1x0tmmZVQFEGUI1gwTSpMMhHCVZcyU+MiKCMOyPgivPQgSse96/CvJW+xyyyk=,iv:MgJS2Q4S2RHyXewd0GD7UGRrOAb1ohNnEd4Be0YtCQE=,tag:gLcmO5IgWPlRVSUjp7gQuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UDBFV0pnVjZ5dzZMSTB6
            RjgzMFZtWDd6YUdETHZZQ3R0VDBvOEZWV0NVCnZUSXllVHd5M0FsU3hiWTJkeElH
            UGVVclV2clEyNFprUWtSNkM3eHg2cU0KLS0tIG41MXhBaVMxdGljWXg4ckJxTU00
            bkJvNWlDd2pBVlA2NHdaSmdzR1FsZVUKT73Hn6mcUjuPLRyVP0lCe3v2AywQo0u1
            xEzsxz4Ad9XUAmBEvSIonDalh2xmJYFCN8TF5tBsuLgzF2x/tBCJAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T00:44:33Z"
    mac: ENC[AES256_GCM,data:p7FOu9Z/I5TkiH+2rJnZ383QSLFLb52JjoL9Vf+NtmKMrl33w/jKJES2Fhn6vBJlWNWOFLQuptsPIYdU/7TyanUXth3Goj48sbLK5CPblNM1Bnpc6R1HNYIN3pDDHqdZxFqbu6OSLEaVyzhbXEv4Lm3CZWCQoC7RjkA8DTJo7SA=,iv:wOI0dpvViGNjWX79bz2cbJ91DUq93Qzno5a5oIwlMEQ=,tag:6a15YeOnrBDHv+NPunX6Uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
