apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:voBY33Re8tzxh5WklecdRNYdIXK59Ay8MeiZEmBc9oRnMM5VVU2bJA==,iv:ZxX3WAI2LoOLyHs2/2va60KzFwyxJqdIq7SBUmWZjyo=,tag:I60PnsjEOFbW8sWSVmg1jA==,type:str]
    admin-user: ENC[AES256_GCM,data:5NKk7s4=,iv:o6UvoGm+fBMMVlEQQ0rrWG2ZMrJRoHkN1hiCKVee5/0=,tag:koJ7COY4WtAYR+YUN6UOrA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOLytDZ1dQVmoxK2dtbVdK
            d3ZoRWtwUEdFbzBiOXFMWHFEN3VxdGpiVFg4CnhmRGN6Y1ExblE0RDZEWGxBMXNN
            TFJrcEREWHM0T245SCs0Q2lXbmNMdDQKLS0tIEJjZURMZGJCbi9aK0QxYjh0dFg2
            dkJCSzIvRjliOGdLOFo3OC8ycWZRV0EKgQIjw8dbv9/8hPI/JMmpvkyTimS4VAiS
            ma/kk6Cle/xUA3fn1Cm89BpLV6ZaZ9qUArDz09qmNXVBrOIQVFnRjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:06Z"
    mac: ENC[AES256_GCM,data:6D3aYWH3+Uz6qrxk0Bn+ShzutwZayBZMzef6iza0p3jYvS9yQ0/NDwfGJBCFduIj3QaHpyJv5ruYky5n7KqCcDNDDfqmJfWV9QlzZu/0Zv/UGjO/UvkF7snG7YzxG5oYsaBgmOXXbSAGNXPaswhibQtTqi/1K/kZogyTPF0EJBw=,iv:MRLK9NZaupzyKSDZ48tUdeNuTOt855cVy/LFMIPW0m0=,tag:PiPJrhXajHL9xYVRQ2hXtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
