apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:/NzCgQrAvXIuH3hInLtTHu6TSfyMi971gwrGOij7mXMUq67idxuNAw==,iv:+Bx6TSKaxhP8KPkU9Sckl6L6TOtXtdOlVl+31W1xpNc=,tag:Z+fixQX0fdwZKWr+FRfTzw==,type:str]
    admin-user: ENC[AES256_GCM,data:XSz3j6I=,iv:6iIxHNMKZb3BLKIDL4if2hzkCGkkffzfR2YyvyZIQPs=,tag:sVWByR1pvQeQtlY3XDXEgQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcW80MTF0QTIxQm44NDVC
            QnRFNVZtcXlvUWJVOGhwL014RVlMSHFUcFYwClgrRzJaU1ZrSmFvRld5Nlp2bkUx
            M2ltK3pZQWxYRXlZbHUwV2QwL2hSbncKLS0tIGh6NUtzOXhVYVB5QkFjR1MvYmtv
            OVo5RlMzeUQrVDVkWkM0TlRkY2diRlEKzZz9FqpcUuErstho9LQL/sd4dTQ3mnlM
            2RpuFEklwhLWAIKQmPigjQQIaOGpF7HKDlLB0KCFGpWwWEbCSZTpVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:02Z"
    mac: ENC[AES256_GCM,data:GMTYWYOcQ3ZFZ6lt47K0gdFdOVKQD9G2X+FYe6m9cmJIN7d0APHVmhDTcxTn8GGndcCDEaJeFAki65i/hEzKACXYWtZLd42HTutc5iZY6MFpbInbmCa7GZjRNMuoNsdE+gUPCqmIvrX97lJhMllMDLMdClGxThyAolDqf9SOaA8=,iv:DbLKF8YADxKEc55R3v5wa83vl/apGqwtcfVc+6r9GI0=,tag:GQmWDLRK0eemaTc7O0GeiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
