apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:gzMfDK1iQZWQxDHgl8/PrQj/zUVuOFbJxXa0qfkqggaZoSWBTexyLg==,iv:OTWIP/+hi+D5v35wq1zzshtvvvn/Na6eL3RSNJeFYIg=,tag:v4GbiJuwWNTOzKSrj6S/nA==,type:str]
    admin-user: ENC[AES256_GCM,data:dpO3d/E=,iv:d1eEuvqmvw/nmogqeFvc9niOHQAqLLi41sQEiYZ2t5E=,tag:tVJ6k+TWsxGn5YFhWAvxQQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNGZzZTYvZUU3S05yMTNN
            REJSOFFtTzY4L29UQjEzYzVqZENWaE9MM0ZBCkFuczB0WmwySWUwWlVycEdSa252
            bVczeStJb1poSDRjZ2RTZmRWaVNPRGMKLS0tIHdqMkdQN3lHTEtxWDdKR21XdXp2
            bEFPaWE3T0FOUDF3aTYxV1pNV3A1bzgKp7Ivw06qr1S/rNJKFfJOVqOwEJPwgZFx
            AFxslnhVfyeSapB9w8TBqKFihdhiUW4ruqAD40IKOs4MGXXl8sYUCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:26:02Z"
    mac: ENC[AES256_GCM,data:j9XTg2DRyofiiJyKBJ/AGU4N6Wi9UjFnNyeE1n86H6blkqTEeEdZ125SkJo4ST0pSdV/uTLd/EOZ7IuYD1DymbL+D3UOSuI9Xua/27wUH9o5LknHkrCMcyuaf4SPDlM50YkJ+6R9Kopr2I2UY0Au3AFcuQUOhBmr09iSa87Ycck=,iv:eXk8wcS5sIgGOVWX4Yc7jFH64mBslUzj7DIOtNzmrfo=,tag:+sD9moH7F0VQzSJUt0A97A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
