apiVersion: v1
data:
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:ANy4kTUWF5n9HxQrad1NbA==,iv:2Gb5CjcDv+HkxxMC3p0D/nhaK1siC4A4X8fS0CA6MMk=,tag:liZ6JmCOaFwd7T3GtGm8bQ==,type:str]
kind: ConfigMap
metadata:
    name: rabbitmq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY3hwS2NuSXcxOW1VWlp6
            Q09pYUhtTTU1bklFUUlsOUs2QUNpRTN0WXpZCkhiS25veEdlZHk1cGxaMnYxb0FP
            ZFVNRHlXbjdIdDFESXNYQXVsd3E1RjAKLS0tIC9qblJ1QnRMOGJ3endSQUpqNk1y
            ZWY3TjFITWhFSERHNEthV0hIaVl2WG8KJ0lmOHKc9LScH+G+48nk9qtWFxkKLwDm
            TtwY0fgivqZfGr5GICgfrFUGDQgNS0etM8lW6TouGKY9nU+Dcz3OTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:23Z"
    mac: ENC[AES256_GCM,data:7NFXZRFKGD4vSgi7xaOiZcaesAHUy4QlPaO+rVN8sOFjCKSgIVK6fU41ia1bst2Z1SjXgYsFY/1tBbiObFeDdaSS7hcpie3tJ1ev+t5ZD2v62cgCtZj8WFErX9/P543lyC+rw2NnS1uXIccVlJX/waQyPpgye/4KxQuiPiSdjx0=,iv:u7knU918TM31yXSXE6A1w29qXYuag1Qtzny9plJq1Tw=,tag:j4AVTXqg8z1/h9M+soO3cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
