apiVersion: v1
data:
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:fPzjFYnNbacOfiFuAkOClw==,iv:brm1Zg3g6/+NfaLp+Qy2CXroPYCoKb6jO/yR5w3CgEU=,tag:s83GvcGixEUtgZwM+dZsEQ==,type:str]
kind: ConfigMap
metadata:
    name: rabbitmq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWDF5K0RiWXpveHUzd3py
            bUtKRnJab3F1QTRYQzlCM291T0JValdLMW44CmNqSFBTSVV1V0czdE5BOHRWSDR2
            cE9aN1dFdXB0djI5QlZkZitJTFBmK1kKLS0tIFRwb3htNGJ4WURMcVRqY0lBWVh5
            Sm9kZGlpL1FCTDhPS2pkbmRKNmtsNmsKcfT6CciB7GKLxkMq7q7LXHYq1oMopMW7
            r1nji/9K+32bnokFObKBfU/PMCPeXwa5HqwcT8ZhE+GYQpb8lihQTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:26:18Z"
    mac: ENC[AES256_GCM,data:96jkTo4kG4PuneJ6kCYVLAR5LH3xT4oaa6zn88SR3TZuou/fXIewQRkXx5c8gQx9YhazvQDkHZ1iM+WdccFD4rKYWD4HjHuA+otwzSAQ2GgxrQ0Re0CS5MgDrcUj2VFFtFZxGHTgCo2OmfdddnSGBOTvL8FcuV7YjUQTA2+1IA8=,iv:HeA8HwiC5p1j163G4DGYuMZQMorYPMjncdwT68PqIEk=,tag:tL1NWismFN7C+pH5qp7teQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
