apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:PXHndCm+sQugArU+oZ3DgvREYruVGW72E0O95Wsle8lz,iv:RUTRHry7b9+IL4opz7e07zJChkpqKjz1pK+wvzoi/wg=,tag:wjAwV7yrDLvZeLIvO8fzCw==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:yXEZypDvV/Hk1BrmjyXOag==,iv:XIoTt9CKE3nzpygntyIAH12PsLdHbPmw8utItD29YOM=,tag:CE1BsZmTO9kHAKXzKpGStQ==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:G/TEKxMLwZYVoeBibQ==,iv:fopDik0ddkvnmWHg91XlfGIgxQxDRP4NcQW0LPE58oc=,tag:N4bsLefZGuPD1qAhF93enA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRGVMT0dOT3FuV1FGWFdJ
            cm9vTmdkQUJpVzJaTTF2YVlUWDdDaE1SU1d3CnNkazBLbUtudXlOdUtjOVZZVUd0
            cDNkZVJ3MDh6dm0yOWQyUHpvb29IeGsKLS0tIEdSUTdnREtjM1QxRDRwR2pQRVZR
            STRabkticDR6eURDSElBQ2tqTWxiWDgKkQj6zep7GAMKtI5oL9mEgFmukIQ2sEnn
            HvALdtyY2QZkm40yxFdox1vi7Zdpr9ZiyiVCV7PIewtfrp9TStZnMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:09:27Z"
    mac: ENC[AES256_GCM,data:7Nfqxfk6xQxkq2BRQJAwYFvY/OMwm1T3OhayAcRREcuRBFVs+tlhnYyOgsF9Rt+QsuNWYO3tuO1bbe8FeVrd5hkAUKBXiVRvN3HR3tu4bX2bQgfT1VPBIRLKnxzZgnZF1Gpw6y5v1ybEZ1o1G8r/BzRj7pcQWqJzKOo4GmDiCPM=,iv:UTS8+3Dz8CO0Idv5zAR66QxPwVVm80n5aH4ZfukqM38=,tag:KMW8o8hn/nbxT57cFqz5qA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
