apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:bpWrCep/hb5WDYB1WSBZ9w7tH6EmD56myRblxM2mbPki,iv:IB7KwmTY0Y/FfG8uK9MS21TG2/TWTah4coQ6JsfVj/I=,tag:cafviD+lH6R0L0zBFaC77w==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:ZW7hsVuYoXPKq5WMHCGddg==,iv:y3h2/O5Hgbxi7mg2s/dDpleDIn6t+PWxdqfZyKFJJ8g=,tag:5UHhD/fzlzyKTqj5kl/SyQ==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:3kODRz7SoARTH/bPkw==,iv:Vo4SClwi+h75f1/nkf+789SGbzPuSP+eNTorHiNOiF4=,tag:ve5fGmCIF0KccO8gRmQZuQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVME5GK1ZPR0FZdUwrS3Fz
            L2wzc0NBUjNjMHJkRmRCczZhNm9tUnl6VW1JCnpjUHNYaVVtazYrYW9NR3FGRDRt
            SVBrcVp6cmFZR0pENTdrbVo5bzFVQTQKLS0tIGR3d1MxZWNSdTZiaWt1ZHNicmNy
            QmJuK0RNYzJqNnhNVGlzS1RBSE9XNm8KalZ5Bc/bkDZEkRWltpHY+J7ZkfYwGO4P
            UTrhOf/qsw3cDgMBQGFL897rWE0WBlWmCPAGP3dcu7RDxOAd8SQ7Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:19Z"
    mac: ENC[AES256_GCM,data:/g5G1hw57cdzQL+Sp78wjQJ0PZbmfsfjq1MGq96jbEzJptp7FkT7AWMLu/0t4BavS7vUG4B8Xxis8DRTpLJLic5XeEpzn7Lqde27DJIGwlpe3yUYN2Xgr9ucXp+xAvbU1C+zb4uX0smX9CYnlC+It3CMh1WxBGoexfyVmNzUtLI=,iv:xMP1e88oh12EpKbPYooZIWwwOMMwYyD9NX28pPqBAys=,tag:XyOvnrQ+rGl7Ez5UdsCB7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
