apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:uyvbfoYrVU0w8H1PrCC/bsdqGu/Q0VlomeJE51+BqFws,iv:00b7jS7ISt8emccXIb6YlWuF6rU0FKG8fgakd+10aeQ=,tag:OipUO3b/2+RpRnu8wFG7JA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:NlEp5QU4EsOwdaBaKb402Q==,iv:RdSmf3eZyFZRy0n7SjXHmVWCthaSiwYshrhvZjRhu8M=,tag:UwB7eK0ZMGlacOTsPPEENg==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:I9kCddf/0OJIAbH71Q==,iv:Y725XHKEBCYlo3zOKnbwO4oXZk0ciNRpOlsYlxqwg0E=,tag:/X8BK02MaWNxfS9KfuQ12g==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcm1YdGw3aXVIUmpXMHJU
            SEdwQVJvazZkU212SE1XS2RMWGlvTUJVZGpzCnB3akc4MVBvejFtYjNrbmxQdjRR
            L0J6UUhsaUwwMWpKWFlXTUpnTkF0TVkKLS0tIG5zSDl5REs2aUg1WGFDeW5HZVor
            dXRXUnd1bU54VkdmV0Q0cWVnN0NGZ1kKI18iBuoSsyCpPWPz0XgBH0sh8IsGq1sH
            rfn8A3BFbQiQRDpi1toyjXimQX8vWJ4tZa7M+rhn5kdOYL58rsz3lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:02:55Z"
    mac: ENC[AES256_GCM,data:9HZXnSv7dCkGIvtl268xL3bKvkkxT9RgaBAdcXmvz3RAHeUJYnarUzzWqvJ09X6SLz2ylv0Mh560X7eabxvExYeqa14/dLeGFhstb0kCuTD5Qrpj4ioG56Tt3uIA7dzm45cKOlPERJYo/P0SEX0nUB9ETwuzltKHfgSZ3J9urs0=,iv:UTZ1KPz0RKEqJakXax2lrDW1Y/8waHD24l4iLxblYV4=,tag:5Y6qsIEfwB+knV8ae2c42Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
