apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-secret
    namespace: immich
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:LOUDf0Yl,iv:sPXujZNvKXAKCz8Xsb30yX9eMyjJ7DqhRbWGgeEXA5k=,tag:9Dcn3qYbH275vRomOQcDTQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KBihACBvETWQNOrr6MTo908gkR8HxDepkk2pX6EEQU4=,iv:S8Ot6IZdLEvMhCIEsOFWDS+z8VC3OAL2kcS5lKBFzd4=,tag:oeKeX7NZqvZvNeO5eNBAWA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:i143a8l0,iv:wBQOsRq/BActfx32snziaZ2eDfM9oRoGRfmesHqazo0=,tag:iXS5FNQZwsdhjdIlbOQNlA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:SlKWnSzt,iv:XWNv9fRG8UNfO04Fzi2+cRiygzUaLT0WnzQjWWCwxeo=,tag:QAZL2+1ko9lP9elNd1UzXQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:/4Z0p/cdY1u63G/9Gbfy+hUOXcxzKPR/0NOZz+Gtba8=,iv:2cuPqdWhqb6mWLX8GouIoV9rRtqRtb5mjIDWxD79A9M=,tag:GMxDlqfHmb8XF7KOSNgoYg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:kOT9CT1u,iv:vnB5MjHmcHmYU22e786MCCHSDp5RtQ9Shv7ORtHAZT8=,tag:15z583KHir5kFXnedK8s+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYTFRVjBTZFI3T2pzZ0Fq
            UnRXM3JZRmlpWWZyeHltVHlHVmgzQm5TMFJBClZoL3docWEweGl6S3FnNk9mZDFJ
            empTSUE3czVzMUlTZm1vd3E5aFVaRXMKLS0tIFFJYmFpOHJtUDRmYXEwdmMrM0tN
            UkI4TEl3a001d0ZidWNyaUpsdW5IRXMKILeZ/j6lCmUPh6FoI0EApljRcW7gwLfx
            3NbnsKtnhwtHZ0/J8IaGSSMyMc3HIDKagoozhSbg/rd09AQKtY+83w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T02:12:34Z"
    mac: ENC[AES256_GCM,data:Mkhc7WR1YxqSjI0McIo0VkyR+rFjWc4+NwkBuBBD9CUY1plfF4hudCGkEj0CLlOsmCkVjRciTeRXo6mxW8YvPMSmIlcVuC2YWPJFMtrHUDXg8mf8Q//rK5YtXk1SdHgBpCgdN3cazplJByNu+F90oYCISfzowf4ZraA/6cp3qVg=,iv:f4am4uDDq2rMdhMmsJcij1AlP1WgnBHaz/A9At87x34=,tag:tb3z05gpEggTlLwKInq+rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
