apiVersion: v1
kind: Secret
metadata:
    name: volsync-immich-postgres-data
    namespace: immich
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:150koqfP1ZwQdKs7dShgse9WNQ/4o2ra4x7V3to/4C12x1Q44BR3ta7uwxCO1inb3nSACNABSaKxTiwTbDQt8oNayvUeOrCZjV53oIfVS37Fjw==,iv:vQnizPYRW1/G61yQZhMiOQsJwFqPuG8M603KojXFm/I=,tag:TX3R6H5lFTYISrEYbi+lHQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:uDDf2z/ZbXVBQdaN6AnZs9OV9Z7/D/4v2ZZPJ179TZxWNuOuq8eiyA==,iv:xNsnqnc3O0CSDRJaIhgB+1WJ82OXWD8tDmg6W82C1Fo=,tag:sZx9f5WPtsFuL6GLUlzKeg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W5E9GHGeFg==,iv:cWF1JsSpGPDONFWGsIHbyYI6OFIw9jB9zjGkJJiY6EQ=,tag:1unH/ePE+n/rLVuUwFvQlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2AAM137gXRnORJKOA6oISu/dNH2bDVYbRED5x6i7//bLmuM8eAvHeg==,iv:uIq9+LrZ9b9w01Q6wEGjOOEyxzVZprrUSdY6sj118lY=,tag:9Yex/PNaZ69qvrAi/Uz5tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QmxRbXFiWHdzbVB1VFFn
            dGF5eW1tMmlzL2xDNTdXaTRNcUdPMDlrSlhFClNNNFFSckJ2VlpDRjN0djI4dDlq
            ZWlkNnRVWUlFL0EzQkJsTFlwYVoyWjAKLS0tIEV6VW5jZkcyMlVUSzRFNnhaSFlR
            WFlRclkrUjVGci9HS0JXWGJyOW51UXcKAnsKOFBnNkxFlf/blxxktfaAWAg7wCBv
            h9085bvGu/SQzLpSJ0XwkHxjbDFl1cRxB7tUQFM0Ljc+1Iyr2qSKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T02:12:59Z"
    mac: ENC[AES256_GCM,data:1uKEYcApYLBZHqNLKgmier0UMvIuZl02roPFqW6uQpsUtCOJVDdBMOzYydsDy2hXomN7n4XKtOkT8KRU6fMVKHghD2CQwbcr7MKs495bxnWVQRmI29c9n2VNrHWctUVDAvKCWBF/q53XSHVY1dDo8VPoQ9T1oYaEwj86TPekaG8=,iv:sXpGMELn72kNXtHIdFlIPhi+vtmRpfreTPHhlM1ytJk=,tag:zU8GGsIr3H50g+rTlmVdPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
