apiVersion: v1
kind: Secret
metadata:
    name: volsync-immich-postgres-data
    namespace: immich
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:F6BJygzQpJtzzklpxiy1mdcK0mCfpAaWw5/+XmxYkadJys/kiqghe0jWzyiGM5ZSFkSYNk1lHWm8/clrWxE=,iv:ee5nE5kNwp4b0jXJBSauWBKuz+K1gSf9zIuTaKRAai8=,tag:NBUTYuo2oVnbD2znS314uA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:uDDf2z/ZbXVBQdaN6AnZs9OV9Z7/D/4v2ZZPJ179TZxWNuOuq8eiyA==,iv:xNsnqnc3O0CSDRJaIhgB+1WJ82OXWD8tDmg6W82C1Fo=,tag:sZx9f5WPtsFuL6GLUlzKeg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W5E9GHGeFg==,iv:cWF1JsSpGPDONFWGsIHbyYI6OFIw9jB9zjGkJJiY6EQ=,tag:1unH/ePE+n/rLVuUwFvQlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2AAM137gXRnORJKOA6oISu/dNH2bDVYbRED5x6i7//bLmuM8eAvHeg==,iv:uIq9+LrZ9b9w01Q6wEGjOOEyxzVZprrUSdY6sj118lY=,tag:9Yex/PNaZ69qvrAi/Uz5tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QmxRbXFiWHdzbVB1VFFn
            dGF5eW1tMmlzL2xDNTdXaTRNcUdPMDlrSlhFClNNNFFSckJ2VlpDRjN0djI4dDlq
            ZWlkNnRVWUlFL0EzQkJsTFlwYVoyWjAKLS0tIEV6VW5jZkcyMlVUSzRFNnhaSFlR
            WFlRclkrUjVGci9HS0JXWGJyOW51UXcKAnsKOFBnNkxFlf/blxxktfaAWAg7wCBv
            h9085bvGu/SQzLpSJ0XwkHxjbDFl1cRxB7tUQFM0Ljc+1Iyr2qSKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T11:24:50Z"
    mac: ENC[AES256_GCM,data:/Rs1nhPQI4nddLEzsWy2dmNdM99NhnJC9SmEtkQnON7JiTD8hUmU/2V8hnsI/mRxvVPVmMRAthwP3Wugnm/z+4VP/PlDhPKk5HP0jXEn+8DON4OWVfskEtyAk6qT9mR1wVO25ISVSAt2kA0LSkOv1e+2F14dp2DwsY4R2OFZeqI=,iv:dUjWRb/7OvNQRQ4GUzMGVGqm5XI+qc7hcXloyabWEPA=,tag:Jggkaa7wijj6S16SLlyeOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
