apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:KgCp2txB8sxwgW82PB4C7YMlBgnVLfvQEkphEU7w+OIqy9GNdmYNZw==,iv:GeVd1jkwk0JMAFcbgzywjPltpN2L1Zmb9Laa5FJhk7M=,tag:d2TbB9kqFfdf8Lh707zFtw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSWw3aExWWUNmbnFSRkZy
            eEp6M1QyeXYxNkpKSE1tTThHVG1KcHExT0VFCndMZFdpa2s0ZnYxclRrU05PWTZ6
            SDhyZW83dVFqNXhFYUpEYitPQ09VZ0EKLS0tIDVkZk13emwzTFRUNTNRRFNrNmlv
            Ni9kS0JHZk9TeTdNRHZJMkZTdWpXS0kKBsaZkD0e6gwRZ5cjEvyLwcz1hf3lKEBj
            Z7GeC1iALCsMiFhf/PnWpP5XzirDHS2i3rHLJkBoPob4fcevYl7Qmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:08:55Z"
    mac: ENC[AES256_GCM,data:EVrHQ8GhL6BfIyJnctoVL/JUxkeMn7Z47GaWNBpuf1BARYwzmPSHCk7LRPijrIwo4qExaL84A9orlJhLhE0spetfDJSVHq/ghSrpkv11J/zdAxY9LKTjfzS5QHgrOR+67xVBENekpGP8F8jgnzBCnzrpF6QVrfvuZ/BHSnP68sw=,iv:fxqHoIvLloUQS5TF+xOAZwfyDOh7M+gwBL+VU4lF9nk=,tag:u+q22776hnkiVtuLNbmXKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
