apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Wfh/P5d+JFisWsfz1NEWiBFA7KqxfYxog8+SPacc4V9Prs6TKSt20g==,iv:wjukNhD4d1hOUxlmOdC2Ra4qdPv3H7NNm1ZfqVDeArI=,tag:bsxOe5fcnJGH+4zCOLWfww==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYzR3eG5ueEVwZlIvaWNT
            eUJIZ0JPMG5yeDNhVWhEUElyZENXaTFlWkNVCk54WUlERHlSMkVudU5KQnZocUIw
            elBVeDlBRzRkRk45VGV6dmxkNjd0ejQKLS0tIG1ubDZ0VFVxZElZeXF6UzVOMHBt
            ZDhIeUFoNWdQVnRSelpGaHpXRTF0TUEKOpwVjOYWAFOZ5YWgxm9iueV6gwFfcVEr
            4gbs5nsTBsiVTQO19nl4jkyxdi4Y7cQmmdRspKZQxsjB3i1Z17vUPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:41:58Z"
    mac: ENC[AES256_GCM,data:ZncGiD4wY5SiKBlfAWWPF0RhdWow2uUkFzgjyYp/kyAz0cSiORv/o+8Dib9wbeVEHO+cHlUsk0bL8jwmDnIlRXAjditQtd+aaJ4eE1Y0dUV0ghaAmJJz8Z2DQGxcE1tQjp/5W8JCgJZcHa5XlJYFiZ5sC301s/rtt+ZExywStkg=,iv:IJFVpe3DykPT3eUYm42d8khuAsOEJr1NaD15CYQaW7k=,tag:RiSbpM5WWeAnaB0blLeybw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
