apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:dhwYFgbxohw+XSKPK42BOW1byBOtVhJkjyZN8PiJ1u1yDvCy5aLowA==,iv:pgrzSdSO5EkR/GwYu/eP4/sxtcf2TGXSN+FzbhwGwho=,tag:FIHFSrfedY0tFhc0ohlqPA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDloeXoyRjhnZjVnRzRF
            dGgvSkU3NXREVy81VlkrQkhIZzNiQmRiVzNRClZZaC9udW1uTU4xdFdKS2RPQTJC
            UEFnbk43K0hUcU0xVjNZNlFDa09GQzQKLS0tIFUzRk80dmZMZHZOVlBPTlE0bTJk
            RVpYSTMxYTVOYUhzRjRPai9IUHVrcWMKxjr/Y/7yyGuuamjgpCPfsHkEvPqkRYfO
            7F3Q9H8Mxp8i7qPHkQ1b4g2XTil/Jd3kg/eH+7kn3EPQO6VBtmfpuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:08:58Z"
    mac: ENC[AES256_GCM,data:Y7t1WrJ0xMhCBM88sh2K1/3TWELaVax+moB0SODs4hq6ga9cdQAlFe4UDb269BDg8d+DE3fDYyjfXBGuC1v3oeG1824EGVVVBknudMsjxSXGJiwSeeJqF2CFq2G8od76CE6sVpEOl98HezHew2AHCJvQC7E/e7PEp12tI2OtJ2k=,iv:cWERUiY3R2gQmBipwb7+uyhOh4BUVvOvEBTzO97PZvo=,tag:PLVVB/SnQiVZC1toOuigvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
