apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-secret
    namespace: database
stringData:
    encryption.conf: ENC[AES256_GCM,data:s4bimuEOPaXuW57y3wc4FdhfUSQdC7v/mapJHco85u/lNyq9mhsiVQ==,iv:Vi/czXUJZ2md8tMA8BKBVUTWe/zMfUX0cVKUJnpBQms=,tag:efkd3e7VlEKV5QXwjuwstQ==,type:str]
    s3.conf: ENC[AES256_GCM,data:p7LJSR5Zyq/NpyIjOyphWMzVs24AgKq3TO7hlG/ooOtrlwM3RtVaxg==,iv:C+Dp8i1Oqb+yWw4bCJud0EzOYUzF1yPn7+3ZCTRFdk4=,tag:YN6dzqzENk4Y49tW6jZ2Mg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwenZKYmUxOGJpRjhKdk53
            QUpsUldlMGlQaForS1ZYdnRxSndoZGVUcFRnCnVSNkY1VldrQ0dmKzBEOHkxZUIy
            WXd3UEhCWWdwazhXSFMvLzRhMytRNWMKLS0tIGRCeVN3MkQ2VjFBUHdONnZBcjlO
            MVQ2SXFqMXlMZk54VzRHVDl1bTFhY3MKjyMXtjQkm40zNkcNZGBr6OeYPC3csFUM
            PdsuDJwB9chROGZ+gDSEAuk+249UIS9EhX6r2JDf3Xq7QPoek8IN7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:41Z"
    mac: ENC[AES256_GCM,data:iuygMt7naYOeBQdwzXV125/+vRfFGoviIiAi6Sy9kp5PWFEKD1lhlLBiNLwq5pzLWYYad87UXMzDyQjHC1PsZsyy9VP/oS/VUICnWi0N/3JPsxlKfhW7+CqrjhbrC+0oee9FYNigv1gJE4AYopOixUj7v5bAJj2zcH0/2ZAV4cI=,iv:QlKKYQR9WlcemLsCw8/+kO6TMtZGFb4Zxpuhiiyb3tQ=,tag:YJfsB5/wLJkp2Ey8l3+luQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
