---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ${APP}-local
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: ${APP}-s3-database-backup
      global:
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/postgres-operator/gs-local/${APP}
        repo1-retention-full: "14"
        repo1-retention-full-type: count
      jobs:
        ttlSecondsAfterFinished: 90
      manual:
        repoName: repo1
        options:
         - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: ${APP}-local-crunchy-postgres-backup
      sidecars:
        pgbackrest:
          resources:
            requests:
              cpu: 5m
              memory: 1Mi
            limits:
              memory: 1024Mi
        pgbackrestConfig:
          resources:
            requests:
              cpu: 5m
              memory: 1Mi
            limits:
              memory: 1024Mi

      repos:
        - name: repo1
          s3: &s3
            bucket: crunchy-postgres-backups
            endpoint: https://minio.gs-farm.net
            region: garage
          schedules:
            full: "30 1 * * *" # every day at 01:00
#            differential: "20 */3 * * *" # every 3 hours
#            incremental: "10 * * * *" # every hours
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: ${APP}-s3-database-backup
      global:
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/postgres-operator/gsfarm/${APP}
      repo:
        name: repo1
        s3: *s3
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 1024Mi

  postgresVersion: 18

  metadata:
    labels:
      crunchy-userinit.drummyfloyd.github.com/enabled: "true"
      crunchy-userinit.drummyfloyd.github.com/superuser: postgres

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          max_wal_size: 5GB
          synchronous_commit: 'on'
        pg_hba:
          - hostnossl all all 127.0.0.1/8 md5 # port forwarding without ssl
          - hostssl all all all md5

  instances:
    - name: pg-instance
      metadata:
        labels:
          app.kubernetes.io/name: ${APP}-local-crunchy-postgres
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: gsks0
        resources:
          requests:
            storage: ${POSTGRES_DATA_SIZE:-1Gi}
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              memory: 512Mi
      resources:
        requests:
          cpu: 10m
          memory: 400Mi
        limits:
          memory: 1024Mi

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: SUPERUSER
      password: &password
        type: AlphaNumeric
    # Applications
    - name: ${APP}
      databases:
        - ${APP}
      password: *password

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 512Mi
