---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-infra-local-instance-extra
  namespace: infrastructure
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-infra-local-instance-extra
  namespace: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-infra-local-instance-extra
subjects:
- kind: ServiceAccount
  name: postgres-infra-local-instance
  namespace: infrastructure
