apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-s3-database-backup
stringData:
    s3.conf: ENC[AES256_GCM,data:t1RhDjOnX6X0E3qyok5xUR0x1HgH79P2Rtz4MFQsxQ7Jt/7i7OtnuyLz2CUEZaC2B036wEnB/OAinob4jESe0Qfz9/Q6NABKMrWCHdzeVdoYQ/vFmVCGnmNOqq4=,iv:qAyUFEE4I7+3lPmeU0YYZWOfk4W8d8nBTuxxRbsnrN0=,tag:tyZRxIXxNReMZWJt1SX6sA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWHhGcnVXOE4rTDZCVHc4
            b1hwY25MYTJ5RmdGeThQL2lRcVF3NjlRd204CkM0YndjeTlJRG55bFhETDROYW5p
            aUNxSTBxcGV6VnlXR2prV3FyaHMvYlUKLS0tIGhnbmpldUwyeExWRXVyM01mNlNr
            aE9lUnZUZlpZT3NZMkF6clRKRzllclkKODXXIvZ+mASwDjW2yzz1zZM7a7gEPrw9
            yzM3py843hMYpnJejmDtPPc9z50DE8DMjBStNCWILhei6pMMjEPQ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:41:51Z"
    mac: ENC[AES256_GCM,data:iG4e14qSXZZy+Mi3SVquDPMgvNcp6WtYEqx3FuDDOsXDusz5B3zl7fzJkzd2KfIljQhKYtzbOqxKU8vMPVysn1ul7bKYowWPWAc6wOw5qBGaXpAv1mk6nGZK5dsDkpZHco1tFZXc/kD4qRCmKmZz5p5xIlIc5xuubKBVliMPDIU=,iv:Z5kUJHGU7vXoCqJum07TTdbDk9i+ePmzIJqGhLyzomk=,tag:wwJq9R3o+VtjuAIlMM9Q/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
