apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-s3-database-backup
stringData:
    s3.conf: ENC[AES256_GCM,data:pGr7diUrYjAJDKLzf8AXP0L8tzQr46Hw2wKztHAZk6IZvUAXRajPB8BY9kSS5InTtggbcGBsLv/TpqcQrmD1OVkSTUuVzqlI1VKmxq60QlfG6rNW3+YQccjYvODb,iv:97qa9MPRShsAPfcS8DpElxQSU6jpDHzBXTAbU7SKoaM=,tag:gLb72q2kfCLTPf4mQDas5A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWHhGcnVXOE4rTDZCVHc4
            b1hwY25MYTJ5RmdGeThQL2lRcVF3NjlRd204CkM0YndjeTlJRG55bFhETDROYW5p
            aUNxSTBxcGV6VnlXR2prV3FyaHMvYlUKLS0tIGhnbmpldUwyeExWRXVyM01mNlNr
            aE9lUnZUZlpZT3NZMkF6clRKRzllclkKODXXIvZ+mASwDjW2yzz1zZM7a7gEPrw9
            yzM3py843hMYpnJejmDtPPc9z50DE8DMjBStNCWILhei6pMMjEPQ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T13:19:24Z"
    mac: ENC[AES256_GCM,data:DT1lYiQ8H/9K6sxNPxfAv3FJCTIT2vozMYVq7FNz9rzRRgvBvEiKF/68u3xwESnb3hKsdpEmz8BOKJSVTQ4+25muR9LwiUkVmez9udx5obA4PqKAH+d88iCzhIBJY1wgS8QrO6DbZz+QeFXvIr1blywSe3qni4yASC1bvz18TUQ=,iv:YooDyvyzzqhMBn5TE2EwdFizKonxVlxSRcQbPKCO3Dg=,tag:rCxMstgyUk7E18BsNI9h1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
