apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:y+SFamzNa244BAROXNzDjbBpFi0C700x7TeRsSGA+n+BOYy3ZA==,iv:vjABUMbQMXjg2iwab4YBmX9roxZPKHuEwbTub1g7tHs=,tag:n4VmJ4QHGUGhmF3CByIdZA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3JkMlMzeFBQbUpQWDZE
            YURZSGtUenJaOVNaUzlyZkh3ZU9GaFFLUDI0CnBLdmMwTUFWUDdIL3daMkNPN09u
            dWtRaGdEYmx2N2MxbDNRMjhRNXFqd1kKLS0tIFIwTzdhSG1RdWFpdkxNMFhjM1dz
            UzMxN2dBeUh1MnZTUFZsTzBpemkvaFkKqBiv/5iGhmk/TVsWe/qhm65cpDWtMRZG
            dI18kFUjbxILA/pbBBeRHV6W72Z8qZsBGdwUUmpy3HcoRktyfN/2ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:48Z"
    mac: ENC[AES256_GCM,data:IobJsoRHaZeKtcho9iDy0U5VT0cwvDf/kSGondsGv++9otPRovev8xFDNn3Xr3mDsZMyzm2ZJcMRQNoRbOQhJNDzLYfz/xg9PvHWQFYFVFFhk+9F6sN5HFJxcBAf795L241ARZMcek87STTGBnLZNRJzCtsq4N5JRwogPJedrl4=,iv:5BJMoJ+uMwz4IyI/5++PK3O37A60nuxgUQwfupxpzhI=,tag:CslSmIzvZ2ep4ZtR6BrkVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
