apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:55Thvgij/EmX46ViK5hZ7IaJDRdfcYiBvd4nlsQWOvx4Q/AX2w==,iv:/iNao4Y6dm0xnn3GFVlZUEZVCdcnPArQiWR33pWuMGM=,tag:6CUMK3wbxbBDKKVmA8vrLQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNzFoTnVHeGk1VEhGZHFN
            UUJVdVJNL3BQQytzKzV6WDhDenVPS3EzdTNVClZzL25BSFd3czRIMXJNaU9VRVlh
            ZDRXaWFCYVdpWEtWY04yMDhOMGFjN0EKLS0tIDZrQ3FQbWMrT2tWQUxUcGRRbVdx
            bUp1RUU3SjUzNHNDY0NORlVMdnFQbjAKUs+QaLa3aOfZyBILNWjt6G42+aTXZC/B
            K6jwRvJOK98mi/h7+7p4DmRkqYt9OfJJBK204xT+rufsjszv2XnSNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:47Z"
    mac: ENC[AES256_GCM,data:WTlhHZFp1ePsRCbBR5XfNSMw5ShiQFarEOLaZIoH8Jdci+Dxrv6XBclr04gM5tSihApJGk/IAdyEFbKQu/1T9G+iFExPbLUMjOoM3HyW27qVI2iP0U8ZYMDfaiwLdN9JG/rR90yTvVVgxyZvKa+RPapxCBWEDXqTiUsXTobmuaU=,iv:T4j6LwcdWJIBgP+eX/12N7TSvMylvQZLVwlCZIMl1qA=,tag:xHqc9NKaNDQfcW05ci8ieg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
