apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:o7WoLHRLj7JKjbGBv8vgjA==,iv:0svG7EW2DTne+gd21k+eDMhtFAtvicuI9kP0s7GthBs=,tag:ttH0wk7nrWW54X2uo0jW7A==,type:str]
    vernemq-password: ENC[AES256_GCM,data:T3Jw9E4/exuMlA2iNyDXHBS4TEmkeeK4p6E0EKGF4X2wFaGDIG1hgw==,iv:mYd/2rv5X8l22P5Zh5PXFfNu/7RoXT1M6irG6Lu8H24=,tag:PGOEeQXKm5kSU2OCxK1Wog==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNnZFMnFKNXB6WDZ6eGFa
            MTRweVRmZ1kvL0FMWFp5c08remo1enhYTVRFCkFvaVFmZVYvRzVkbms0cThLZDJF
            UzEwNGY3ejVKc0s1NG1yYjNBa2R2U28KLS0tIEZnYXlieW0zWXVtbHZvc3Zzd3ZO
            Rnljb0pQOWdMK1JMWHJGMGpjNHRNSVUKsyfVvEOQq7EzU1DGFwoKS/mefP0e/90d
            dH/uxujaLO230tJRBNfP+x8Og5UGpG2uBm2CQSP2WA1ve7Ybb4W+Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:46Z"
    mac: ENC[AES256_GCM,data:g2w5Uv2CqAvUV+FbJn4Xid7Is1fWynbawzcjbPtI7Lxsz3iVkqmvR0EC5Qcvju/kZKhU0Hm7Dt/6QkyzCo5sUdgshmEm30IZSBEArltcJ7NVystId1+aoZ0y2muykOY8NffnG3PI+rCk1C4YIqEByd6sGbH5SA43Mw5VI01UwBY=,iv:y4n8PWG13EpMc2yrW8fw4YBakAOCRXqSz4XCFZBhIik=,tag:w3VAQl3r61t73hFtJTsY1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
