apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:zaKdUcu+ESeWdNC8IMv02w==,iv:F7o+XIU0QKqNqyukKgM3lN3vN75iTNwa9ch95i+MRWE=,tag:gC2+7bJuti9rJHuAdXlRfg==,type:str]
    vernemq-password: ENC[AES256_GCM,data:t4BkhJbyFo9VihJZAXQw3KONWYpIuijfxvKzFlBrzoFWXjFhl2HPLQ==,iv:ytSVYabPO8P57Plwz+3eFB1Xj2j/4jOig5O60uePcnA=,tag:lVZFhESqPnLRXYno+oslnA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RnYxZlVMY1J2TDBKb2sr
            MS9yYTJnOHpnWjBsYzhEUmNyVzZDTy83UGhzCkExdittM3N5UGx6TlM3VnUrTFEy
            dXJNeHRiaXJsWXIxRk5ZOXFLWlNNZVkKLS0tIEV2VHJFOWFxRkpZVm4rWFFqcXh2
            WGRiM3RZZ2ozRS9yTHFnL0hlT2tDdmcK/c0UCB7VrtjyUm019eoqLaXfC5wYD3xJ
            1jXm4Br+hEdFVAjD2g0EnZ4+CjF+ePySaxMsDpTQM1d7bVDdUj6mzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:20:12Z"
    mac: ENC[AES256_GCM,data:yZ5A0m3izIusttFSIEPhNHSpFtevv/rnaw5N6mzn6pUaEWVfx4tljQWjMGpVrT0hznWTavqnjt5Q/k9i6rtUaKK157Z/TBJ5jnFeb9FLJk097zuY7+t50Lky9tQovkszkqTLX0lEDry2Q93IBvCocc5yQj5jatOkEE1qTZT86Xc=,iv:dVYB20TP7POFcaE6pVzm6euu2rcG25HtT0sJwZlWeFU=,tag:iaz24Q4/xe6vWfebwHPMbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
