apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:v78hIJ97Hf1dK1ZFCnrQ/w==,iv:utR2uQof9NQy4UY2DOhikpiHI+/IPhlNTlMhZjx6/24=,tag:x6AXTkZL20jfkQWiFPEJrQ==,type:str]
    vernemq-password: ENC[AES256_GCM,data:Ay90YXvFh8y3P4BWP4DkssKN04Nko97pEPfW/JUP53GV/p/TYcjJ/g==,iv:nyYDQQdemc3gGRvQSI7dtWe0pr/xYoIP7SeiWTltCJs=,tag:txdNWxNBSFn71oOcAJ5Stw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNnlrK1NiakMrVFZZUWRT
            MDF2UUpocXFEc3phRmtrMWZNSXZwMGgyUVZzCjJETSs3em4yaEdyQVNmNE84amVl
            emN2SmtwelpzRWg4OWp3eGR2MTlOMUUKLS0tIFBRRVkrYzdxTTZrUmpQWlh6WDU1
            SjJwRk9jaDNrZDVLRFVKb3JUdG40UlkKuX8APfxVuGlHni+4lh/jS8wdFFvcSk1M
            9s0XtJDjI4yr9DJYETm+WgyJI6GQSpnt27Hf0o4tcJxW/oBxmYYdRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:09:49Z"
    mac: ENC[AES256_GCM,data:UdDicLsEF3XBro+7REdgvwQI86rWnWyDpZzKk26GqnVxubTB6+tsw6BpsvDf5pkXpJQFWNsV229Di2fWLNvLQwPYwwKr9Oosi3HTOTrKmlmuP7f60xmuuYdX4OLcNEUalal5XoF9rDAQPb27X5YoRx1eQBsDxzD79MDNBNln5og=,iv:HGY2Y5UcDodoyTAcG8GrnZfJBYuH5xDrFbYrYPn6WgM=,tag:yMM9PAtcnJAx0wSNtVUE+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
