apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:hp0vE6AIhczL80QEp+REbnAYxozn5xUxJDRVDwWF9BL2DyZgzQ==,iv:ZlhnpuFhVl3wUcAaEAC4p82HsGbsliSNfMcWlkextlk=,tag:hyBc5GNWQwwcSAbwgpXDaw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTXBRTFBMcUpnbVpGMTdT
            YmFRSmNNVnNvZG9lbHhYbUlwZXRVMVE3NW44CjZIVTlvMzZUYy9VSHE2YXluZkxI
            VEM1WjlQK2xYYkZjTUJ2ZEVOY3ZPVVkKLS0tIElCaUl4ejl0KzFOZnNaMlJKeXkv
            ZWFsWnVZYlhiejkvS09qQVBJUEdmN2MK0NoIL+WA1ifi39D+AuyZ8xQNkIIgvi9e
            6HjZUM+giiv5h8jZPEvVnx5ImcYpKqPmjRLVfcKNgQ2B/GqXlnLx7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:03:23Z"
    mac: ENC[AES256_GCM,data:fbYh3npuH/rSJwmDMlwOaQfk+xQ9MpbDAqFAHry/Ho/PZvRRexBNd1TV+nFJrG84mAYhopxNSBUmWMHwRCcevhLwleDQ4h/O30+KDPSOa0nGQwD45HZz1Py0s87QgfKrV7GjpXgVmEvhf2Me4bbuK2V00A/Qman9DJ7c0pMgBYE=,iv:aKQW+f2ujPNj6uOxBRbzKyOt9xblcF46VJYXJtHMhBc=,tag:WPYE1yfZWsUxGoVTrou/7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
