apiVersion: v1
data:
    DOCKER_VERNEMQ_USER_VERNEMQ: ENC[AES256_GCM,data:57Y/+2AK522A+Nt+gh2TYQ==,iv:KWpkzss3fhxf59J72GWBingSPy6h0x8RvbY3dEAfUNQ=,tag:K48OxIY4MvOPyydqitTUkg==,type:str]
kind: ConfigMap
metadata:
    name: vernemq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVXJMS21qays5dGFrdHp1
            NllmZ0Z6WVhOcVVrNUltUkZLczNTWFVOelZVCkZOcnRLS1RxM1hkT0hHTTF4d240
            RFdTK1dONTFCQVk2eWY1c3FNQkIrVncKLS0tIERzZHV3bEJSL3crdG1QNFpzRytM
            UWh0NFl2Nm80ckdRcE10TklnaGlnZmMKTISsj0DPf8xyDHHXUoteKApi1FEoLWt8
            5EFtVNx6IRlOvBzuBNZW1ZCm/zXwsVVD2Sr3wE0JQXcc7mAmmfB/4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:09:48Z"
    mac: ENC[AES256_GCM,data:WNBXPRyNVnbuUN8fm9t670sIOiRcPqMP2BbKGY95tmVfx/3uS5iFbbDkue3RVxYR91h8vZZOo8tVitbC1ybD3uRbQxO33rHOIl9bbtyL6D5Cj0Nt6nX3noS9I84bidzUUaMNjgqDqFQOJE/xPcq0ATtk4L6cEPjKz//6P5HkyvY=,iv:aB9TPdEMl/A2bfsVB9HTwQMzL1DPSYuRuO+0CAy9L1U=,tag:T4qd6x//R8c9l9bbGJEedA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
