apiVersion: v1
data:
    DOCKER_VERNEMQ_USER_VERNEMQ: ENC[AES256_GCM,data:0L9plXPVuxU/hpWcXOmqyg==,iv:mplmgDsg0lUzZ4BAkObBo6Qk9VBCE/PAvXRM3764NOY=,tag:ZJc8TWiIN0z/Ye5GoIlGOg==,type:str]
kind: ConfigMap
metadata:
    name: vernemq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbG1xR0pxSTlXckFsUHZU
            MGF0emtteGRyRFdWMUlOZDNVNHBNM2hkazNrCmQzL1RNNDZBODdiNlhFSjR1SXBv
            QzJrT2ZteW1qaTcwTTZpbkF3cXE4aWsKLS0tIFUrckNJWnBIQmhxell5TkxkOFJH
            NzBKekpuTCtIVTVXc0JDdkZlZDc0Y2sKOLGNdaeHTSR8/pCqWKlJ9qvlDNES6Tbf
            iu+0Ej3ZE/qIefF+V3g4lMm2gPFDelQVO4yg0kijLWhYooTjYsaYAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T18:15:16Z"
    mac: ENC[AES256_GCM,data:gkdAxOqQ8AWz6b7H2/K8+CyOjGNgu85hz4Yyy6EnXwLrxMcqIFHdFvMypYb1SLXbN3gwS0IqJN3r6ESQNsyrz/JkmaQzIV2P9rDLFYl/ivbXZtPXFxd1WTxR21hG8/Xs+KAuTfMNZpxLeXHXF+ScRb6bZugkK8Qdvn+vh5p63WM=,iv:o7qaCxcjkYx9s1QBn8dR5rG4VGACvGKsXtH5IoQ6OjY=,tag:KPa1yKT/IfCixIHzIoXZOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
