apiVersion: v1
data:
    DOCKER_VERNEMQ_USER_VERNEMQ: ENC[AES256_GCM,data:eStNo4R4vcEAIiP1G5OHrQ==,iv:H8Jai5DEpCZlFVTMzPjaGHP2fJ/ZbsVteT1Mt8/jqXU=,tag:wq+tbHsp7q07lEV1lmTATg==,type:str]
kind: ConfigMap
metadata:
    name: vernemq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MUZZSWNFdmpGWlFjM2Fo
            dHZsckI4YXN4RlYwRVRLTTNLOEx3MGt4M3lNCmZDd1hKempnUnI0YzBCZnFQNkx1
            enJ1UEtoSmlRWDNsT3ZCaituYjB4aEkKLS0tIHBBK0dnNVdGT0VCTTd4TkZEbkRz
            YlhhVmQ5cGZOblJFNGdTV0dMRDRpdGsKaLm63KoxgBhR7zTk3dQoCwT9Gf8T0Y9O
            1IXmoCmMi/axUDxhHBjzbFmXIbEQmOG+9TudC5E2xS0INOy/VbJcsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:20:11Z"
    mac: ENC[AES256_GCM,data:GVcgsOV7S+/20KhDHPyOeoZkZL3fiPCyeQibgnI0MUYgZOpDmf915UlSgVIc/FsD9TGgFHRdGQaiOF3W5LT8QQpQWULWmSvoFHbk3mWoW6dQQPdrPXiH9TWMaa+++WIQgWtSgysU8y6q5V/fIpxfgYuoUQZXcoFg+AvWL/CKHOo=,iv:MDtig8irefq7Z8nISINAvdOU6fkKTOw5ozeMTIFCEAc=,tag:KtSVY/lIxeN2JTvctyZ0yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
