apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jyAENsdr3u+K7NWeoEjz1n5ptHVC+D3Zo0Q32sxIkqLYwzStUySy4Q==,iv:0lZX6A1rX/zruIvOwU4cucHsggmQ5pTFVFTrKIIxKBU=,tag:ewKj4P8QK+q4E+cAx5jaSg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZE0wK3J3NEJmTWRUdU9l
            eXQrNW0xbkdIdGQwRmdVV3UwL0c1bUxnZVVFCmM2aVUrYzZBMEU3U0FoM2IwVlpS
            SlNTQnFOU3ZWMEZ4ZFh0WXBpR2w4djQKLS0tIFo3VDVXRUVFZHJBMTZ4QkdqdXdO
            UGJrbkpmWTZOd3V3NXBROXBkamJQS0kKwkuqhBGK7XADiyATANiuuX+qk8WxtG1z
            mINwWQgagbTyN2egKm/6uVvTmWD71KZoJibfE52cJxJAl2g1pI14Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T00:53:28Z"
    mac: ENC[AES256_GCM,data:cWbBdgmOTMMW8YvBA7gQe9wCI5L/EcXQMG4bvlfGK8bfcqNP90hxfqYZfqAWMTJ9g04OANvoT1GIxKqt1f+3EuZS/V7vpc9bFW49HKaj/3q0HT8tfqqVaZkH43CGN7qirqMEAYI6SwF071DweHScafSQ3UUHuEJytN7CnpPwuI0=,iv:CC41//HeUSF9GcWDf7VKE21vHx1VMRB8plUgt5rkcog=,tag:yeC6snDcboxRkh45j6uu3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
