apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:x4Kj4aDF3GsF6/rV7KB15jG66iabIOk+1/VwIxenmyyWI0zHOzBxAQ==,iv:IcJ6qVy1BBsUmgJmFeIBvLar8IhARjmBPpYlXBEA1yc=,tag:tHL0PAxoO40b/BzzzuWaEg==,type:str]
    username: ENC[AES256_GCM,data:QfU6tcc=,iv:kLgxfpKhjCs1ohxShgCFC/oeYQwON9m6MIrEo0Hs1W0=,tag:r85RIQfsi8nIXfblifg6/Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVld1RzBqUWlSSWlkdlhn
            S09idm9PZzBra0hULzRVVWFKL1U2L0R2Nm40CnZ6UGljeERzenppR1ZYcHlpSU9T
            WTZhY3FwSVZucmhwNVczL21uSHBrNVkKLS0tIFNNT1UvWUV1a3c3ZTVWYW1iUUh6
            NmdDNEI5YVRaQkp3SUoyVGgrTVc3bDgKGflOI/VakWaOOdIm0nKPZSqG5A/1nXYj
            VK/e4cVC07leVpbY3QmytCZE0gDVlgmbW30JOUWH7Z9JcotfmvupIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:20:04Z"
    mac: ENC[AES256_GCM,data:1CJpW9enqA6DVlmDisMJF5wVcO/OO8cPFdK/nfyRUBVM8JUN4+NCF24sYATO/RB+WZ1Jd1sq/fToNl3hhltVKIYcqsnasKbKzjLtgSDCFNooYCDiw6Rb+Yb/yofE8LthCSsbVGnmEydwj+iF1DqDj8+RGz65a/fcFLCfOHsRB+E=,iv:QgoqhPRQYNfBMRNKJO+rqQ3BD4IRkz2fMOnxfzDpqis=,tag:u8vyytl6V9q5dOb12+3Rew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
