apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:3ProKLRtsxjdVE+Ra+M9/9Rhgao/WApN7iHFiZY/xJ0B1u+Tl+CseQ==,iv:yEOtxVZLBT1UdVzz/z3gAU66vDCH8Yh8xgX0Dx30RhU=,tag:SDGIWzMR3V4nR9C0KgNF/A==,type:str]
    username: ENC[AES256_GCM,data:6+pXayg=,iv:eoROX16A4NkXxxcuvlmy+fZG7CzQUioZd9h0v9yl6BY=,tag:oBnjB0/E95SjVCtk35Y9Qw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSGpuYlBsbGtnZ2FObHJY
            WlZlekNlZjFWQ0IxS3N1QVA1Vnc4NWRKMGtNCk14ZllHaE10QkQxa1NQeTRCYTEx
            R0krRi9tUDlvS0VkejlhN2wwQkJETUUKLS0tIDZXK2dGQ2dNMVI5dFFpWEFkSmov
            eFl3M0lzeUNDakV1Uk5RV2dPUTEzVXMKzFLBFc6HgoNF0WGPrJDngIal1fdCWnfV
            lVrAAxM65tS89zWWGlqvBaXntxFrDQoUhNofwRDFumPRaNRa0PjcCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:20:27Z"
    mac: ENC[AES256_GCM,data:8aIdCSvYCGrBz2ubYXb9M31aZO3jfHRd/53klsFxFTQCN8yetuJFDmwQ929O/4Hp3FqCXMav4eq+VQmLX1z7SSrba8L8zzqZDmJVXf18HYQIOaxtkC2TyZqwAe2Pe89rO2571nV75BjurEglt1Zr1foYQg6ixrjkxcTOVxnanTY=,iv:jmOvJVmw9n1sAib0U+dQl3VlXqQDe6b8xD+FJ8Lojjg=,tag:RMPWrc4ZHzUDsgQEU79U5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
