apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:ImsM7nQY4SOxPEtkJbXIeJdMqkp0oI0Kub4/9c2VqbAQaZ31YCJhIg==,iv:5YxmtWrOnL+1qFO8aquh3AYrPxb0lvgBYusWxd4JkKg=,tag:RsGlSyZDZgjmVGozjMGpog==,type:str]
    username: ENC[AES256_GCM,data:fW5utKg=,iv:pAnHwHBCKHgwwxV72o+FQ0Fyd9BbYeS4kTwmBzU258w=,tag:naFKYwEmPWqBwc9MWvTQ9Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMHN2QW5lUnV6Tlg5cDRw
            L3prM1FEckg4MUpwVWlsUVFFbFJzd2tGaWtZClNDL3VjdG9tWHlsYWxabFRLTUdr
            RHpUTWFKOHo0a3VYZVVRWkM1UzVua2cKLS0tIDUzM1ZRNkFKdjNlRjFtVk5FRHhq
            Z3dYTHYrMmV2cmNBWHEySjVKYkhNc0EKX42jR5kHBLPy5zh94zLzmTBSOZaBjTQb
            kwVUtNp80jX2lJF/x7edH37knV03jBNVtz1QkpijLLi3Zq4q83VwDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:03:39Z"
    mac: ENC[AES256_GCM,data:lUdfhy5V9WTv6R5SGNiqQv4nFQ3tLLyBUsW/lf8wTAMy+Msps6n8nbaAGgEPX0yL0zjLpVmpUcf81jjhjR1WpOUaSdsZC4FTeL/ykOL33XulwylARwCH2/6ILB9BGJ3F6dyVxxOx/KVqUdkDWcVkKL73TLbVtJAkAw+9T+GW6uQ=,iv:I1ITO3DEML8Qx1tRFL+pdzYnLZa1LTQE9RkIvL+U60A=,tag:+KPqbs81FP7icH/iec85BQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
