apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:UWpBu/ex1g2+cGceHiTczQ==,iv:j5RiDP0J/R5HfMmG9IvXwgwZ4MY9O48/qltsYN6Fe8I=,tag:+6aQclrGfzqs21lWoGPdOA==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:qNEZXeYfU78Lw9dqRguT,iv:cnxclnetiELGTS2rmj2ZDmwnnqkEq4IlJD30jtI8Si0=,tag:aC44Q+HcZujWolg40wl9Xg==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:EiD25BU0u/yBys5e53IGMQ==,iv:SHuKIRirRy+29LhErwK64HCP52uUrTp8oR3lpcIdx2g=,tag:hOehTnmFlFMFif2/r84nCg==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:t7sAT3bh0wYsgD4tqCFJwg==,iv:6dzkh7z9/Rxiqh9+eEICscChJUO9TNuq3S5oplmxqyU=,tag:VSkF/IpdQAYAsHfcilRftw==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:9bbA1ZyhhtCbQEIr,iv:gjmOFEFzgkHvdLglX9RtPFsioeVnaX/A7BqZQvJFz5E=,tag:hznl6Mg9XajtJiFlpvxOmQ==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:3zc+p/WA03ydoA==,iv:1RQvsvS2l7wGSHobipEInnn9p+0w34M9UEMa75ck36c=,tag:Z+1Gjtw1rB6pAM0QNWFOfA==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:Qo/XeY5AypRmDuEWT5lG,iv:pUByeZc9zySCtLDSdH4w0ArpA9jftibKXPaQgINsie4=,tag:khOnj61vKO+cQgjabXhG5Q==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:Ph4z8GBOaxAn/g96JCCToQ==,iv:xYRGJeM3ccOx3CzbkhSz5XillEDr8sMvPUcWxIEKnhA=,tag:mIJ+bv5KHL74+YgtUgQ7jg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U1N2UlBoSGRJRmc5REg5
            QVN2UGljSlRkc1g0NFFhRUhsMkR1dEUwY1QwCklOODNqUlNQU0todWxzMC9Ea0I0
            OE9TOWlOYmdPRktndEtFUzN3azExTlEKLS0tIGMwSkRZWjN0ZHlGOERKVmcwNU1U
            dmdLM1gzVkRkeWFXdzRuNHVXYWRkU0UK1lHCPzc2zrkOrxTHgf94k74qQFhc/wyV
            tEEoA4FuRDEcjyrKPOk+X/Pep6hMS6DM1NN58QkJHyUz1x7Yf6NdoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:01Z"
    mac: ENC[AES256_GCM,data:YVTT7jgJMjNO9MRWwKb/jOBcCQ64kZE/D3XDUFp5enyFFgXzOjGYaG8/pTrSQXljEZ5C/n5j4kJB1jxSpMDfMpNF1MeJOqr4tsG8QkQlqtC0Nx3V+p0JElyrba/tJdU5m+HABbH/vXPNV68MA9fRHRgj+3YrpYOdarEzpfV2gg0=,iv:I4O18+e6+f442xnWC+eIoIFHpbSmdrdkMAyVWb8y7Hk=,tag:LOxabNm17K8xQ4lcRuS7xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
