apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dz/gLnhLi8ln9C03y9Tjd/T5,iv:S9gRfaTF7YdE/dQWCzhmHmJg67ZK/IYhL8PusfASq5I=,tag:ogAWNZkg9WCUW1eG2fwKbA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5wl5kHNRy/FNUg2NLfQo5Dce6A9MWs2DHOpP1i5kn8TO4TUA,iv:QYVTANX+SRqQCFVgkwkt8+x15/fggI3MXaq9vyFt9lI=,tag:hA+UhcmiBeCGv37ZlUyugQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4Rp17fLDVDTqJ9c=,iv:Th59B2TMZTbFAjupFu6i6FTJJsu1jebmuu8chdbmKUc=,tag:Yb7K+IhULkeQnk5vsoXDNw==,type:str]
    SECRET_ALERT_EMAIL: ENC[AES256_GCM,data:VvZ5pU5l3wCLizItXVzaWAyo,iv:3ah3o49R8Tm66x4Rrqz64WTwk/nNL4OXnhPEOXvqH1k=,tag:0k6vTcNUShsf+nzInR6xZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSnMzWE5sWk9QczBOY0dQ
            ejZXaHlHSHhwdzVmTDJ2cjA3TjVNWFhoNm5BCmsvY3RyT05VMkFSZ2x6Qnl1RHNs
            UHI1d3BzUXhCRWdlYWVYeTlHcjRpWGcKLS0tIHNod0prUjIyT1V3TG40aEVhcnJn
            RkpDbkE5NHVRRlF0U2IweEY4enZFUmMKzGq553pZR/36lXUdgr6MZsam1JOPDkKt
            9rh7t4+3Dp3iP63D16d6qzTmYR/BBtkJDlKHVfB8giVKGoAa1/KMEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T00:53:01Z"
    mac: ENC[AES256_GCM,data:P3SqGpiZRbEDEQgCUaBXjLN/A9FJcfv+T3ubJBdX1HLCWAYG/b6fUzoD0SCmSgLsY/dO/bf8Q3b/YRrsldzDjW/469PbLrSzGqgOc52axOZqrj7KUTzD/CYjRANcGI1j2n2yXbLpR/9gzUvWjdW9VU54ZQmDlzyFnNVtXfhQVE8=,iv:FeuXc8U7X57PNz0wvkQ6aZ2MaJhYuB9Ym/1/YZX+75I=,tag:nxo1Ux7fyswTgWGJArL2Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
