apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VZzgpgAeZcIZmohs8wGxG+Su,iv:FVtuJsLzsXHRXP0zk1ch6c1hBEOUE/IomcjhPQsuKJ8=,tag:/srmTBJMS9JpMbXY0213VA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iSEDtF8x2hWBv6yVMAY1IYf8pGsfSSP9NxtVh+8dRTB366cR,iv:/CUZpkQQb96oAQNUEATiqUpLqsKgepeK6OM1LA4o9NE=,tag:zF5sMObK+yhVttKOH+ItRQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/pQzrSYReST0ZGo=,iv:4vXBjRVkPBTr8wgpu2jZr3iXn/gA3qtSQ+QbqmopIFc=,tag:L8RW01x301PJRI9xm2vbuw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMmFlNjNHL2lLYkZENUtJ
            Vm92a08zVlFVZ01PWUp3dGZYSmxxOGZXWFNrCk5VVzllOFdPSVlzY3l3Uzkya0FY
            VVBVVUdvU0xUZGNFRGZqQ1g2K09od0UKLS0tIGVkVThmbExhOHFJUzk2WHJhbXF4
            MU1lZENKam92UmY5SHRkMFBnSXBOc0kKGGH3EjHd1EKekuqWlH2WV2xmdY09Jh+6
            ubcBYR6zjZ7ZV25qvtNu+u4+/cNrA6eQLF79425hT04NIMfIl54CyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:25:52Z"
    mac: ENC[AES256_GCM,data:35/z1GCWf78INtA9j9Jodk65tDIcRlfAKqzS4b+4sVjHgJQX/l2MnnzYacFRj4OS41meFdJH9wdB/whzxldMVc/K/hTiQo+sndSaT4cTxXjQ+FpBwcDEykL1FOBbO7OmZRPQ6BxEWYlhTgFuaxALaGFzANQgn4sjnbYJP4iZqMs=,iv:FC9z4NpuHqv30NovBsONlJ3k40sE5S86hDRBQ6wz8UM=,tag:NmHJf7qfMerxCt7H4JXctQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
