apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:xpp46pInilKR2FvAsbVvXQ==,iv:huc0Tv9B6n+QOrtjGfEUBS6S90qTcbDjWOH0+bwoncY=,tag:ziSca6qa1lA0Q41vtz14pQ==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:iUmHGYizlqyijH4lZ0H9,iv:GJYobGPBQDF8/LlHR4yBvI5jMB2eqqz4CsDUvDfk2Xk=,tag:LCsIYt3JRUL44MyI+ruLTw==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:NMUDTQAsoUbjqlftw5zIhw==,iv:CLuu2PCdHmDju3NBG4Ih86CZPNYp5FhAe/RqsuYVB/w=,tag:SsJp7U+/+CfqHqfYrwiUvQ==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:7HPYFaiSLRH+FbjvBKVWeg==,iv:3M0wmGJmPsSMhcbeZVUDju82GvVugvQLw3bjC4pJz4o=,tag:NQr42ncepnv20cWWtgvRuA==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:98jLtLjUKNw8ZphQ,iv:QKarediJu9fKmW/R1+FqNAamKcAewFFAYVZlGG1fgDQ=,tag:epM0R0QA/n11IsJNFh9NAw==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:hbEevvJ5YOJ7jQ==,iv:teSbRzRlGRR4qTGJNCgJVrVBEdqFLOUKlLaSipuUMnc=,tag:3L3I2OH5+7ccfPpqUhLIyw==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:GPu9rlrZOi69ytLHAqcN,iv:iJhqPhKsAdxgVJG3Na0Q8aoP8lnzJKTybBGe8tkdMFA=,tag:eVjCvhzxNzvTMMgOPdMMCQ==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:POKi31XQBwt14ryGOaB3fA==,iv:wjoRMpc+moDG5Np9MjaF/rBlLIGdibO7KBkywApb9Rc=,tag:iUbdNXUXC0ne7bQKxU4F3Q==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza29OUnY5dnZmTnNWODJs
            TDlxcFFNVmZZM1lUYUJ0T3RkYkF2UlJYMlQ4ClVwbDlFSnZObFVXN29qMnM4bnp2
            bGQyNWFHQmpmY3pXWTdBdy84aStsWlkKLS0tIFFYanBYYXNzWnFzMVJhMVhTYkxo
            Rk40V3p6ekhqVGFhc216NnRnQzFBSncKa6gXMy1LTfnaN4LFVCngTZa0EjWx8ipw
            hqwFwExUTCxtkwwCCWMOK8cyv4VhqxLLDMFkXWPk/epEgnTKMotibA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T18:14:38Z"
    mac: ENC[AES256_GCM,data:ZWLaL6UGgUoub6k+u7BEL0UQfMJJZ1Dth+OkLcYGk6aVUgHvgdiEfPifjcawsvS55k70fOT76YNM3PNGtgZC8gN6xuiTdUGEu9kIKVTIN8Eqs9MbqKcNdjfDjC+aHQRJRaN8Ea1DBwogg4SGm6zN7Dskw1QdUuoqIqo/7Yq/ed4=,iv:0Bqpw2C8QvomyVftkdkrY5wAA2Vo0RPC9xmft2iGRyM=,tag:WD5H5IgKYc6h0xwQgdnIIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
