apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:arSb0lBYZerVmiPxNq7WKyay,iv:z1PpCErywBUeGznaYrgp7vUWIVRgWX5tGzarH+VfG0A=,tag:vE0jgZHOByWGT2rSOp0ORQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EbnK8m7PpZnq6PeaqFdKeFSvrSZIVHKc2dr1jRGrCOHnBOWZ,iv:3H0txdJUnkCZYnivH6lJhoVqqtuf9pPtSCHwHeoPemc=,tag:rd+1qvIeZI8aY+AnHQAHIg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4Pi82SkllUMBG84=,iv:p8uD+iOrDuPWI65wX37EG5MVYywPhzNQigLN9IczIME=,tag:vIxSXuYVX4j52eBHKxbsAw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS20ycmxvdlYzb0RoaWFv
            YzVERGQxbUxFUGtnUUk3d1dLRjVDbll2Y1RVCk9UWjliMlVFelFwOEpibjdMaTlO
            bWM3Rmdjd2g1ek5WdENMWkliTVgxSVUKLS0tIGxvQkdOTTB0SGJ5NHlQM0VGei9w
            S0V0S2RlWmNPUCtRVDR5aU0xcmN4VG8KjXgZvGyLZsjv5HncG+nZmuHEifbDquBt
            1dq12bPlXDvcSYkokXCahKABsR8uQAaHneXFi6pPMNi8OBe/hx6jYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:00Z"
    mac: ENC[AES256_GCM,data:4Fx22Ddt5XuYEBbslO1YcQaZ43nN/mTFukJdwzL/aqq0HGMUrNl7Zn+xSVDH6WeEsQoGm2YDwx+jwWgRGODhB5ZJqtUM4uQJ4/RoST/P6bcNfCkoi5oeF4881heZpFe3A11co/RKkU4p4J4ojvhvOk3sxkQyvcpuZqpakUdSlSk=,iv:5AALy706+Gg36fcykRuneu9hMtVb4Zjl6lvLCmeGkfQ=,tag:V1ZsJQUNwxMdpWJwDY5Eiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
