apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:nrZWJFnZ9MKvaWL4qupdfw==,iv:m0yddVg2SN4oWvmvEmyyE0Js6QS6h50p4/lRz6ryZzs=,tag:2FYhNj1dCw4KQuioB6VSCA==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:yTDXQFJzG0O8oVbA0/ho,iv:Q7MULFAdGMEPW4X+vF30vWMHMKIZULijICpY4GWsyJ8=,tag:+2IHbeX+L67oYhCxmACYYg==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:A6/PTqj0PJIDs4ZPBSkUDg==,iv:pATpFjgvqlzc+IuexQ5pn12sCaNjATu3TRwBvoChKiw=,tag:3gN0lHqPymNK2qixHLpuGA==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:2MgeYbc8HHfqUYRc195btg==,iv:Q9sOwFqPcwDlWSvpw2swMrds3DzsL/GHw6x9qQfwsAw=,tag:CA2rbBqcv73h0rVM46dcMw==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:cPVMoV0Q9cUnJlNU,iv:MiMNfA6XNXaJOmJFleVN6TDeXhrMh5XMWewqvB8PcXQ=,tag:jgikaG8iF2MsYhV3moL/sA==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:2JQRgfs2gcZPxQ==,iv:R4cpZoFdd/skX9Hgjjr2VL4oAFkzAR7ZkTF/WQce1wA=,tag:UkuhmuXEzdJyPUmBX1rTGQ==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:70tnGfZsGVPSvhzEobjw,iv:p5caBpF8nekjvwim/avLKdEbgS78UvWAti3hM9IgMOc=,tag:5jABxLw4gb6sfyu4pG+Iew==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:joCAnC5okhNp0PP9tD0QtA==,iv:hY+PYcfqWWQM6Pf7EOArTSy7cLbK25f25yDoQ6M9Ns4=,tag:IxtCRWEYz8xib9z7PK6Wrg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WGpuSmF3QS93YlVqampo
            SXVpVFI5eitRSEx6UWdISGl0aVhaYWpMVHpVCjBsQ0Y1WkxFZHk3TkE5RXd2SDYz
            RndibDlvMnlyZ0tKNmpuaTF6Q1NKQk0KLS0tIHlqd1F5VFNITVZoNmN3YUorUmk3
            MUlUSW1lM3JpRmdyNHNCZXFDUStYNUkKj4y3sficEl52GjC+cpyXWMAA7R6UnAod
            bGCUqgWAfRg1CU4uPWzsulMi2TIJKj376bcsWK0BX364beb1Wpl/Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:02:30Z"
    mac: ENC[AES256_GCM,data:G7icOk4qLQfNwCkgnDXaaZTxu3SMdbo9pAVuMaMmdy6BJ9rSqtPDHN3iN6QJD90J3g1rjekF8v8a5xFb7CbP5/hj0WJzmSDwvu26b5QD4+JSXJ4+8yfHyIcoh0POr/1uFaZxBNbT4QX/uWuPLXNu/qdydBDhvvqoRDQZZftQa5E=,iv:lZsbQpsFfL/VMfLQSBceyyNZIW/ouUWq5XFGZ6gim94=,tag:1Plw+BC26/+R4dCam1+VWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
