apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:sCBuIT5UN/aICA==,iv:hYW0dJ97oCUmA1KU2dwpOOhi+M9vyLLrGF8swPOjy54=,tag:wN04mMuKKfABCoL55soE3A==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:SOD+SjCN8O/KRBfv7QvS,iv:g1X2GjFLIL1w5PzwYldDl/KXo8W4OXxsP4ooirKhfBQ=,tag:rAA/gdfEdn/ezJUjlLoE2w==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:PTs9hsVYiSMct8/XV7QyPwYUdo4QYIjlv/X8uI4Qno4Af7OS9g76nbPyQKOfcGw0QEJkn9lCyRGehfjgDntoIHvk,iv:XfCKdS2g7Q8JErdMRLywrWZ2Izr7G6NGkGgxrFXRkdM=,tag:dfS6kbz13jeabp6OzMKJyA==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:wm/fDqd/7i82VKxMzdtWOecktudbpgMkPrGuSO/2qDPjUPVQIofAhjmSsI8+66Pdeuy5idNOZsbg22h/Qdvts+E6,iv:OYrfCeXM35/zSnQINUJ0W8irvZbtfziQrHQ4qc5YpAs=,tag:M8maFUq6wBF/0lhLVRAI+A==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:Ep8lSlsLoDmviTMastob3g==,iv:eRCzHi5ZlTwSL6RHIilSbfXxY8fkRx6XnwydtdEyVVU=,tag:1KPosx1XobwHs9bcdNvFYA==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:DUNlNYa2V/Xd7uX1/O+2HEham7FRah6iwG+iYOrJBgLyDaN8eK9unw==,iv:+9rgmB0UXZy15UqyFG/W2O4+CPEknmDWdeebkaCfKww=,tag:u00zGRjIJIwLBTQ4CGhcTA==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:gt/YC/IpAliUc1jEmdt0sqO6DtmLv1nJX7apcw==,iv:NRZZDSCuCchjlZRJ5U2ZX21SnPswGf5GhMVRftMIRDE=,tag:ByXyFB1/s3eYxURFKnvGww==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:0BqtWx2e,iv:n1lViGLDmIANQR13IZvnW6UBp/g5YfqJI/SNnAlyxLs=,tag:M+k6dzJ1+3diLZudE2A0fA==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbWtTMGYySHRMdG03TUx3
            T0ROVlJjbUNyVGdka09vV0NSVzF3TXZhNWtnCjUvTjZSc09yallHN1UvNDJRaExT
            VktlOVpnVE41VTBGb1Fyb1RIWHJLZlkKLS0tIDVUeElWOHMvZWlyYUFodkxZNVlM
            MGZiYXFOUDNQSnBMNDdmdlJTa2ViY1kKTxpAY6AT9mvAOZGSMJ/fC+YPGHQOmlFM
            QETF3dlvBzie1NNL7JQ+0T5vTpLH0ahW+x+ho8T3M+/OR5o6d4+G1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:09:19Z"
    mac: ENC[AES256_GCM,data:r1xZu9zg98uZFInji/EMpVIwv2mJS71uioElGwheoZYAHATDqfNC0wNw5FE+xO1kLUA/RHIwAtoKTrZAatwLmI1uOufENJrlc8HHFzKQgEGosIuM+f0HSvJPYkgvN1nsFk4T6Z+4vozHTvFI2q/18PygONSAg45tShfPbynat90=,iv:QpNxsK0Lpv8V8kHiVEIXYa6IsQ2Dyf38IIiFgmyLEz0=,tag:KwUkcjCdYvuMPIeffDi7Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
