apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:zmn3xjE5FZZ6bg==,iv:Vl7hbDDiXiEdLViBudb2kecTe1IWDXzK9pr3inohEzI=,tag:kRpCjdYEZ503ui+mB9LAeg==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:sJiw+YwwBsYZnQKawm0k,iv:XyahSHus9LhkLCv1JcZB2ngRuLt42Qe9xvA7bBII+XI=,tag:8v7WS02HTiWAPHm3MRl2yg==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:4suOmOnsK0nNsFQ8d9c9cOHS3DmRtQbgaMi0qbLc2EiWtw9+vHj312k2r67lgvF2uoPurfLluaofW20Ua8zO5NsG,iv:hmPhJz+GA48iH1TppaCyF/A6BQUowRNDjgNRLMI/B5k=,tag:LAWR8UrhgsPS6Qv3HagJ9Q==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:ihd2Isq+OBXQyprCrDqZeIGrKV34ZpVMnXIL+9a57fFfGV1gL6r5ncCddysB4v6VCPjkEDAgWxFjzgDeNQoDE3iz,iv:mrVqeOThKd59k+0GwHVcSLEMI7Sgo4j27/Jm20efTBo=,tag:D6UbnA4AgWLGfaOGeeIKKA==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:5sy6j5HB1vz7hYTGtTju9A==,iv:q1fP60YfP7sSpZSxW/vfCwBYtNiu+g3id4kb9MHl09E=,tag:2xyPULNbQZzm2FOaOziRaQ==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:Pw4SdVXeEZLOjv5uZBdXpqpg9jOlh5LA6S4+RiKxUJ0QzTTDbrz48w==,iv:Gj2hQGpyh/z1+BFoM0KHUHaSO3NumSMIRy7bAqDAsgE=,tag:Prev4fUjP57vvRiCwsg0NQ==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:F++qekH886E2DPLsKqMVCWUwRTvqsfV8bHuAuw==,iv:kmvwwusJIJNNjGyLpb+m2lr2PB0VyKlLD1KdTrC92W0=,tag:WzJV0kPLCge5ohTlJB4AkA==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:N6umq7on,iv:oKqmV+HRhm5eK+KMbf56L965L4UD3aWNZvmv025QJU4=,tag:mV9/XlgIi5WwYhs+p7dHeA==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVi9tdjJUbkhKRVRPZjMv
            YldvNUNYbEtOUlJBZUJoRW85aHZDNzNZQ2tZCmgweFJGcVpTYXVwZ2RnS3hPM2s2
            ZHlmV3ovOVJTT0VwMGxkTzJ5MEFwaGMKLS0tIFBjQk1nREtxZHZ6bndMYVM3R0Fy
            RW5KRXhSOEdzWkkzVWFNV3RkRUt4ZU0KdwqUI041S5KL1GCUDA2zRt3/Y/W8xfvq
            KEvZIX2ezGy/2sN5Qjm1uoADFSdnUY2C+sD9SbbOIxme1YVJ+NTmVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T18:15:00Z"
    mac: ENC[AES256_GCM,data:yq+R34vR0Frna2GLi8+tdyVnZYanrsC/W8cbkzS75mOw6lEGNLpkILRyokNorqRUmcYZ+TzE9h73uThHPhv9Un4DNZPRpdNWyBYcDEuyZu8JqDZXegtQ+Ueq+ilTaFOtJSjqGrG2EEWpLGbIBUpKQsi/uMpWcJV7hXVIeC7EwiU=,iv:cP2UXTHQ5M8xCnljbEPmiotHqnzNWGB+D+eTnzYB+5Q=,tag:V4ZGGy+tw2VypBo7ikMIUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
