apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:3YQmr5lXa5DRug==,iv:LIXGT43ztppeHU0I+9Wvsc07Vkyh9l+SU+0RWQm51GM=,tag:kyBkqSAdy5v2pRP/FPEgSA==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:pwndUIQH1+l9KV2n1hFy,iv:lgyWBMQrTrhkSy+s97T4TZejPylKCVya36QoBiCYd7Y=,tag:5Njhns2wMPAahqK4WNKzXg==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:sO2v/oxoldb7s+u667Sg2fwzPAX2fFcvdiR90JCgsC2B+tbn+shUgrQ3un0V9Gp6Z1EtoNJixqRfuDF9Wo9SnMqr,iv:uHAR8+ceJOIQbXtm5ItOunKYvgf35ALNoz5AcbSMH4Y=,tag:I1EVK7kxw8V9s4VnmQgQCw==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:tGnmP3dEV5hTmo6TUxW00ZjhDy7BSBUcjBxOKJbNLig44en/2kU37mEdsARui94yUBN2KXDPfIMHI+9Mdseq21T2,iv:Bcp9U5m/WHpHSoBeO/xa2lv1wKtgs4mSTBspm33MBPA=,tag:nNFAb/x98cPW/i61GIMDgQ==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:sc4ikYOK+0TeZWNCys0bEA==,iv:B5N9sbKIRpfzcZMCk+3p3wLxn199wx+ANewW4EtR1W4=,tag:7f+KfVn1T9FAyyLayA2x+Q==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:oNLpyOFiZkePR4ycdIiDrB1sND37DsSV2keIC/Hu1BH8pR4UaBCvBA==,iv:VLyknx0rd+tDeff/LtDTW9tUeC+RBnpou1wSUJnXRkM=,tag:6pKHD7Jk78jOtdRaPbxxNw==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:cxqDsNxbfVs+LHlIpG9OVD5Uqeu4vdZ9uHLXyQ==,iv:99f+Y/LLtvbCVrXzYZTzquJj1/0O9mitWJ9iLm31Apw=,tag:5+RSb4kw+8WYXZHM+hZNHQ==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:czYIfkAG,iv:NlzYMIs8AdrAYxiWa54QtPIys6LLkyE5ZHefsBJEYMo=,tag:GZixuHTaZXjnRLjF9rAGZw==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrem9kOE5QN1paL0NyaGpL
            WEdlbGVMeU50UTlaNnpsTnBDTlptY1VHYWpzCnZwOGIrYnBRVDB0Y3hsbkswYkow
            WVozTmlzdnhKeVJhV3BDT0M3UHZCejgKLS0tIFVwbVRZSDl5SUpaNEErUzNNeFpk
            VHRUQURwUWt6R0VpZDFpOFJIQXhWTGMK14rcCBnRN9vTxy4KgpbtQX72mKMQHJ/u
            hceZ/HpsYKaFUQKa2kL/2N0M4N1QnksspO5p6ZPk9IIZ5Rb034r3xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:19:15Z"
    mac: ENC[AES256_GCM,data:p1bvWn5gbfPm7CLvw8s9LDOGurfwVhU3ffPCrCdx4BcGDL9/e0Tx7ef6ACfmPHd6WdoL4HLE7w5YnommuZbIUtoKsgi2OKicGoawNq2BlAWwiDM5SmwU4MHyrOrTPVLANBOQ5ffcZVbo0EbXsFQJIbIHbLaADyKUfeep9T+RTGM=,iv:VjfYiUdrtB9g9LCTxPZktFECclWWfdyYEziMEPaf1XY=,tag:rMwWtkOrvLodkZSnV1ntOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
