apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./storage.yaml
  - ./deployment-agent1.yaml
  - ./deployment-agent2.yaml
  - ./deployment-agent3.yaml
  - ./deployment-agent4.yaml
  - ./agent1.config.sops.yaml
  - ./agent2.config.sops.yaml
  - ./agent3.config.sops.yaml
  - ./agent4.config.sops.yaml
  - ./minio-secret.sops.yaml
