apiVersion: v1
kind: Secret
metadata:
    name: kerberos-minio-secret
    namespace: kerberos
type: Opaque
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:w19b5cV5ZGBf5C4CgVs=,iv:LBJjnjontToxpUukMM3RW92voRlz95Xp3036v3strho=,tag:TXV+hHnwcBBkEVZs4FY6lA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:9uGI70HVHuWJpjggSALwiLLc+t8MLX7SM9ql4Gd5/w==,iv:9i0f7X5mkrFkjCsbs45MbeWX7cyhdKJBkhyI05MUznU=,tag:gbrA2FnFDgBM2M2P/OTG/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMnhxcWNzOUFKTnRjaUox
            bWJsNGhoQm1RWWZHUUt5Sk9EWmNnY0JXNTBZCmlTcHJXNWsyVHZwVWpCcVU4aGI1
            Tkdxem9DM1hDTmtUR1ZOSk1sSmtxdDgKLS0tIHlJQlNuaGc0RVJ3eXlSaWVtZTZH
            Z2RqQzdoUlFlZkEvQTUydjVhMXNwTmsKzp/L7/7ryI2kI7BtoPfUiHK+TJ+BKjf+
            +ahRR1Jq8+NHHdyab40NqeU9Bbctrzz4Nxq9oU/+OMcbjvZRNc0krw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T14:55:10Z"
    mac: ENC[AES256_GCM,data:rsx4PonrK/zps6TTP5DYk7d/7iMGrQVCO0DsgUfT2OfUMjzM/hHUv504KeTPX8hoioBdKFw0TcaVLFoUvYG2Wkd4c8pEeNSPmpDy//UaAApij7sHkmFatfpllUI9S58e5wIs/mXdx826i2xu9zK+yOjUnvItP3LyMxn/4kTmE50=,iv:NwUE8pss+hOq2KKDr4QYb0U67xmpv/M+2YfTKtQ69/4=,tag:83y3EVpgAnAZQ0egZE1ChQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
