apiVersion: batch/v1
kind: CronJob
metadata:
  name: kerberos-minio-mirror
  namespace: kerberos
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: kerberos-data
              persistentVolumeClaim:
                claimName: kerberos-data
          initContainers:
            - name: mc-alias
              image: minio/mc:latest
              command: ["/bin/sh", "-c"]
              args:
                - >-
                    mc alias set minio https://s3.gs-farm.net $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kerberos-minio-secret
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kerberos-minio-secret
                      key: MINIO_SECRET_KEY
              volumeMounts:
                - name: kerberos-data
                  mountPath: /data
          containers:
            - name: mc-mirror
              image: minio/mc:latest
              command: ["/bin/sh", "-c"]
              args:
                - >-
                    mc alias set minio https://s3.gs-farm.net $MINIO_ACCESS_KEY $MINIO_SECRET_KEY &&
                    mc mirror --remove /data/barnSouth/recordings minio/kerberos/barnSouth/recordings &&
                    mc mirror --remove /data/barnSouth/snapshots minio/kerberos/barnSouth/snapshots &&
                    mc mirror --remove /data/barnNorth/recordings minio/kerberos/barnNorth/recordings &&
                    mc mirror --remove /data/barnNorth/snapshots minio/kerberos/barnNorth/snapshots &&
                    mc mirror --remove /data/backdoor/recordings minio/kerberos/backdoor/recordings &&
                    mc mirror --remove /data/backdoor/snapshots minio/kerberos/backdoor/snapshots &&
                    mc mirror --remove /data/barnCharmer/recordings minio/kerberos/barnCharmer/recordings &&
                    mc mirror --remove /data/barnCharmer/snapshots minio/kerberos/barnCharmer/snapshots
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kerberos-minio-secret
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kerberos-minio-secret
                      key: MINIO_SECRET_KEY
              volumeMounts:
                - name: kerberos-data
                  mountPath: /data
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
