apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:tBMfcPSOVEO/hwxZXlvqgEh/bihoudpvJ10iwTVKBP7zuTMSoen616EsnfYhWEl4Xfb2ReEbbvctXvqbxkgPcJz7e0yWadFDUP1ci5GZ70C8D8nF31yd5PHI0vqhyG19j+0kHVpOdz/gyoVS2RUQlQIQ2JK3iw==,iv:cqfwDiEynfP3laf689oL1MOJbwTou8odMQ+0G8LZ/tw=,tag:MJYyELAwGzNzUq7iV2zf1g==,type:str]
    smtp-password: ENC[AES256_GCM,data:bZkA7eNgv6vj15CqQ9xaT7fG7Q==,iv:4qjvoGGbsJKOR1HgFoNu6uc4IzuEHV+tCYrLcbmWcaU=,tag:SIjZAfLOx8qJ7ZrT1WJAmg==,type:str]
    smtp-user: ENC[AES256_GCM,data:8riw/b70lVjA/QikB+ryLGvY,iv:EjKMjKn8DBsTBED+xXoyYqrV4b7Basj+pE/ONmT0aw8=,tag:7yIUAVAfAuqm976sRY1CUw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUXM1RGNVSDQxeW9uU1pK
            NGhYZ2pJa1BwekRsRDg1LzFndXJHVGUyaUVvCkNNRDR6aVFEa0xUVUcyaWpYREFp
            U054Rk56TjIrSGZiVFZ5ck1vQTJvOG8KLS0tIFpCSzMxNHhjTElXdFc2SW83R3lH
            aVMvTWpoOHVzWUZjZVFoMFpiT2o4cHcKbDbE0BoiI6N63RaV9ve52JGpG2cfWg7Z
            JCFsysVioiknITfCb+f5uVaKs5Kp2RJgbPDy0pWNPZP1/GNASKFh8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:09:31Z"
    mac: ENC[AES256_GCM,data:kTou2XnetTIQsQzePeygFfI0mA6WH3+cmggyV32t/+Wvqj/2Tlon0LT0ybx3SQvDEr4EnZeqMH0krSM1HL4ITBM95qiih7nMehTSoAiIjQ/UVbCnmZuKiHl0h5DYuIjbeExliuGHAW88EnHuPegty/WfDDnU1CYUjqqOWwxsGRY=,iv:eo9rzJQnsmWNPi7Epqb2t3FZrtk6xI3aB/kUILV8vpo=,tag:oFG7WnG8P0uK5j/lJ/tOtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
