apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:sq8EVfSvVvbxdUE1aUxGnBlMdEIKjC1OP5+UNm8tQz2X03a4mfP9+Sfe7oxiyDKNFu7PBNuzmTchOwwFtKHS/IuaiofyVLkNWCxLcqG6axh3rlmChfejPf+4BI3ze+bWw6lBS6MLqV0dTG1iSqBV7CFk8ZhJqg==,iv:VQF8wPM/+FBiRLm2v1RyNjw2yoz7ULENrvNCswrC2Gg=,tag:uCt+jXoJPasvJpkk2tgTZA==,type:str]
    smtp-password: ENC[AES256_GCM,data:0mI+UzyMdSgNgBcDHOK10CynNA==,iv:EqZNjLZ0nRf9W27GkqZhVID7uG6cP4iJTkUzVVxldvE=,tag:r/iQqURJxIUkSfOu6u6izA==,type:str]
    smtp-user: ENC[AES256_GCM,data:OLbT5oKgvfT0GWlaWRwTsVy+,iv:bR4GnIor42MX7J60MxC43w04Ix2gGC/PCPTggI23ky8=,tag:3NyHmc4Gl1DCXAL6ck3mhQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN09ZQngyKzdoY3hFTExQ
            bXgvR0dZTjZ5ZVVxczFNSFY1eWQvc3d0UUZjCm44S2QyMWV3MERCV3N5T1FaM2h2
            bzBiNjBpVEYrZ01zbHhZbHpoNzhRVEUKLS0tIEJ0ZkdHWk9vNnpzWXoxeEhJQjhr
            a2NVZXEyYW1BOGJFZTB0TTB0TXpzNUkKSyHJaDvgLWjt6A8VFENuTA15oq/feXt2
            EAmvOTQlHPx3TG/hVZ27mM7F1Xo7bFNaK9cn5pHe7tkT0fVM6k0gRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:30Z"
    mac: ENC[AES256_GCM,data:F3yXpwDgNjelC5kim7ueng9vXJYayP00BPEZuCCRuUYnfUFYg4cXfPcq4C4P0fuV2GVDnvP4qXrrmI2urNFHr4uIF4RCdUY8QnUctGSG/oFZ3T8SB8SeZZBe92CrHCW8SDzAoeI+9zvQf2QS6GEvVwbudvkcqWMnGygmrqvi42c=,iv:HXfIEjqAZdPFAdXd5Z/oJZ4cDow6eMBuUfJSUNMstHI=,tag:BsxTMPk4z6FMMdTgT6l4eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
