apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:YXw6fl60kxZPPZlmFPmvRDvrtqrPXfakFe8qbed1RbhIvQw6hJqEQKO4sXb0F+TPEVZB7XLyFL2aH2GVuYbyuM7Wb1aD4a9yoVFnJpMguQca6PsrmgYhCIbz7A7g+6jjd4POqNYJGwwytp/ASdYGnC/gmAhPDA==,iv:zCLl3iWZ4bPvQzOGmK+IYk+p9SKo1R8o7N1+G1s2b8k=,tag:/hWvl1PxNPt0a3ldA3IKyg==,type:str]
    smtp-password: ENC[AES256_GCM,data:A+CQ+HP34xwgIRQTFhllo91rwQ==,iv:sNQjSgsOJ/VYXSrS/RGmtllzHTTqFYmioHiDVZFqRIw=,tag:P/nm1/HNIf8uFO4ipdKgBA==,type:str]
    smtp-user: ENC[AES256_GCM,data:nud+R4rBG6PUP5hs+yhFeLwR,iv:JEAnO2HlEGd72/qDHWn44CFXJkohaow960pNliqxUns=,tag:4XpnTeg30rTSegcillPgLA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRjFQWXNJMjJmNFlhS0ty
            UExXS0JXUWRtZlZDbkwwQVRsSG54NURJM1JjCkJONTE0YkdDSVVxSWVVMEZzTUZU
            NXJRMkVPN1VyWFJ1d2NVNk5IL0R2ajAKLS0tIENLRlNtYnpLNjRKUlI0OExuWW9T
            UjM2aHNBR1lYOHFMS1ZtYTZhU05WR2MKpONkpE5UeDhmJlKAHBh+nf8z3ySNhgBp
            h/IExdIfZ+EsjDeY1BHluR6qnTnOcKuTCBmXxMeww6MyycujmTa8vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:19:53Z"
    mac: ENC[AES256_GCM,data:vFqs2/ymFFh/5qL7zshce/4Z5Wp9oEjO5nS+Oko1c4W/y0hHGLkn4ThkFYD77Z8gqVlRGFapQEAAPB1j2GNiAoMikl8FGQl9/WA81IGu3VU7ToEXcmiNtxrsYO85BqKhLxtAhSI22ilmYuavWvFLhraRD18KAcDAlZFA0lbI5Hc=,iv:hpIV2XWKpr/eZe3ZVCZHigSSW0+CgnpDY3Ys7GeTZKY=,tag:LCJ4FUhqsI0lE16yxnlNKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
