apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-secret
    namespace: vaultwarden
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:JbWxx/f7g94CXm6cqVX+F25t3nCx7/tLd2Dos4GHN8sGgxWgMuAeSiT0tfaW1hErtNi4R2A=,iv:qFLUK0Vk984ZjfK0q0O0N4t/mg2/8wKPY44/Q/xLmNw=,tag:8wAsVAh0sQqEVjYsq/jtJw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DaBIGqcH3PVK2bfbOszF2v/RjvLBRswC1O8/cGQ4MrQq1F4pVFdxQQx+6Gs=,iv:CuDQOu6f47Kb97Ko8j+u1yLxSio0Wg6W70xQcNvqgso=,tag:eA4ojDoNKrE6HpBzBt3eQQ==,type:str]
    RESTIC_CUSTOM_CACERT: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R/odcLdG5A==,iv:XIaQU53wj8n+71JDN41rFWLQDSGpBj8P89WXGOMPGgQ=,tag:jBSnTTF1vCXOAibL5cRFwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LlrEcDM183Y8WtaUy+0K5TMu+U5Zk6Z1L1nneVTIVA3wL2wRilOXRA==,iv:VDIjKlvTSpNdh7PIkf3e/6hVrpdtRcqsnLWaTzOe9fg=,tag:oCz7XWeWRd/WP5isKWYmFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFxVEhFNGJqancxYWEr
            Um9qU3BRWENCZHlLbnQxS3c3cVZvSi93c2lNCmlYQmpQalJkelpEL011RHhrWVNQ
            b3MzZkNRSEFibnJvQTBlZzRaNmxoYVUKLS0tIHZzVmZXSzc2YkpoWWpUMTlRV2VQ
            ZEtudjI0UEZCQkg5aENYTjcwd3lENTQKcl7UFEV/1ESCNlepgfHDfKN/9UPzbvQw
            9NrHpgX7+5zNWoabWOZz2byQtSDYg6IjQY//ID8shkjZJu+QzDbLuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T01:12:11Z"
    mac: ENC[AES256_GCM,data:XhtmAore/ZfhJkkkXXP4LrdsPFRa979KHLC7gIjxpm+1DFYxonaFZtzXVO7YTSY8tvBN/D0KfF8nrM4kZ4HwyUVHxVHL8zAx8isGnCHsYnYFNM5xrMmLjFUTNq91QTZ8mnlo0zQgK/Cay6ZXWKBs+tx6MKlNHizuaBhSZNYYnNE=,iv:CLwRVQ7ZWrOWkvT2qXyWbOzjHOackMvNYkyXGIHEsLo=,tag:9Z5R6Sfyt33E/3HYCZHtcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
