apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-secret
    namespace: vaultwarden
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:3fwLrq0rXHHbqMgJjoebAhamwf2+PvpcV4bdRa2o23X9wrbJ40zBGk6/3vz+LvCRwoU0uyBnrmPv7N7YU0yu90cJCsM53pWctg==,iv:Y425ZRJF4sLElVFFav9X5xOPZNiP/ZSKiQce7+7niOs=,tag:2nWkp8LybXcc3pxRBurGsA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DaBIGqcH3PVK2bfbOszF2v/RjvLBRswC1O8/cGQ4MrQq1F4pVFdxQQx+6Gs=,iv:CuDQOu6f47Kb97Ko8j+u1yLxSio0Wg6W70xQcNvqgso=,tag:eA4ojDoNKrE6HpBzBt3eQQ==,type:str]
    RESTIC_CUSTOM_CACERT: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R/odcLdG5A==,iv:XIaQU53wj8n+71JDN41rFWLQDSGpBj8P89WXGOMPGgQ=,tag:jBSnTTF1vCXOAibL5cRFwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LlrEcDM183Y8WtaUy+0K5TMu+U5Zk6Z1L1nneVTIVA3wL2wRilOXRA==,iv:VDIjKlvTSpNdh7PIkf3e/6hVrpdtRcqsnLWaTzOe9fg=,tag:oCz7XWeWRd/WP5isKWYmFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFxVEhFNGJqancxYWEr
            Um9qU3BRWENCZHlLbnQxS3c3cVZvSi93c2lNCmlYQmpQalJkelpEL011RHhrWVNQ
            b3MzZkNRSEFibnJvQTBlZzRaNmxoYVUKLS0tIHZzVmZXSzc2YkpoWWpUMTlRV2VQ
            ZEtudjI0UEZCQkg5aENYTjcwd3lENTQKcl7UFEV/1ESCNlepgfHDfKN/9UPzbvQw
            9NrHpgX7+5zNWoabWOZz2byQtSDYg6IjQY//ID8shkjZJu+QzDbLuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T00:58:32Z"
    mac: ENC[AES256_GCM,data:VRVoZ8vNPOPngGjouPHNym96canz8nVPHANVFFcYPk9uErCcsTdZ4PJRkraG0LlBJuYVFdvgTof/sgQChaL70FTKrb463d9DR6BhANi6sGFMosdqltK/tXYPHtKmAFHHkEm065Ch3Q5c1CQepDlK1+/t1y7S3BB3YBOb2ALdxP4=,iv:MNOZfVbrslktUYgsE3KF2wLEOQNAgDCU2RrKKMQ7iEI=,tag:cIiDpQmWeLfK0P+vsm00jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
