apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-secret
    namespace: vaultwarden
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:e3tIDXF2oaBi5pvJluT3uYgl22smmWh5UDFu7V1rNLBEzSzn/451mUEN5bEobDzVeS2sM9w=,iv:D3C+51TBcoyNqK7v7WOMuHkiiDhNn4sPY56AdjOmJVg=,tag:mvMPMr4Ima0jxFUj38FoSg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DaBIGqcH3PVK2bfbOszF2v/RjvLBRswC1O8/cGQ4MrQq1F4pVFdxQQx+6Gs=,iv:CuDQOu6f47Kb97Ko8j+u1yLxSio0Wg6W70xQcNvqgso=,tag:eA4ojDoNKrE6HpBzBt3eQQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R/odcLdG5A==,iv:XIaQU53wj8n+71JDN41rFWLQDSGpBj8P89WXGOMPGgQ=,tag:jBSnTTF1vCXOAibL5cRFwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LlrEcDM183Y8WtaUy+0K5TMu+U5Zk6Z1L1nneVTIVA3wL2wRilOXRA==,iv:VDIjKlvTSpNdh7PIkf3e/6hVrpdtRcqsnLWaTzOe9fg=,tag:oCz7XWeWRd/WP5isKWYmFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFxVEhFNGJqancxYWEr
            Um9qU3BRWENCZHlLbnQxS3c3cVZvSi93c2lNCmlYQmpQalJkelpEL011RHhrWVNQ
            b3MzZkNRSEFibnJvQTBlZzRaNmxoYVUKLS0tIHZzVmZXSzc2YkpoWWpUMTlRV2VQ
            ZEtudjI0UEZCQkg5aENYTjcwd3lENTQKcl7UFEV/1ESCNlepgfHDfKN/9UPzbvQw
            9NrHpgX7+5zNWoabWOZz2byQtSDYg6IjQY//ID8shkjZJu+QzDbLuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T22:09:26Z"
    mac: ENC[AES256_GCM,data:+zaTNtFSCstPdMoZJzyGKOBdcsQjYvTr1j/QW03XVEYCbZU9qRQSaDEoJiNGFO7fJ+UwSGqsDgVDFGOD/HIbM4VP/7J3+8fGNXd+MAp43Vs+FoeoUNyS3CbgjtRKAq8WOZNVrA4l66s93YJKOSmZJCFhQmmt1ugVc+yu0uWnm70=,iv:WqAPUXURkZqoJsXbIccH2y+kfBTJgVBG2rVUI7l8Wgk=,tag:s9cOxdmW96nEptQu9BZ8Tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
