apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:HgjqHgODim1eU3JzasRhWTv3HVfsjaKc,iv:qRi9Z+vQNS1Nx7IqQTbmVd2u4nUKD2G/bABZZKm3O8I=,tag:ixx8CgpBqjoo28x6Ren0tQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZE0wK3J3NEJmTWRUdU9l
            eXQrNW0xbkdIdGQwRmdVV3UwL0c1bUxnZVVFCmM2aVUrYzZBMEU3U0FoM2IwVlpS
            SlNTQnFOU3ZWMEZ4ZFh0WXBpR2w4djQKLS0tIFo3VDVXRUVFZHJBMTZ4QkdqdXdO
            UGJrbkpmWTZOd3V3NXBROXBkamJQS0kKwkuqhBGK7XADiyATANiuuX+qk8WxtG1z
            mINwWQgagbTyN2egKm/6uVvTmWD71KZoJibfE52cJxJAl2g1pI14Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T01:59:41Z"
    mac: ENC[AES256_GCM,data:37QiZ+XTRtwSZ3pNjqc2Fyuml/x0wplPb38lYYnMAdsiycNkR+oLu9vJKjP7NP2MCyfP44JxCJ9s8NeokOTHDo82YeAqw6TAzHX/XdvkEKThyMdz1G0v22ydMU1BmmCjkwJWfGCFk+c6Gxt1nEDbIN7sprkO8UC5yJTI1GYFex8=,iv:72PWlXClv5kwR/MPoJYvIxxuuMfdegvj05s07Zzj+y0=,tag:WmNJWy9MIKyesbo/25niUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
