apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:64ZB4e1nyrqr8Q6bRKuZ3IswGZrKSJ8y/A6Vu/foajvPkDGt3d8EIA==,iv:oHm9rXPjFPMj0Ru5EcOlVHgCezJFfp8Qrlg1mW8wNro=,tag:0VSrB5Iv4wmCdOjaF9He5w==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcE5lanFGREJZZUsyZ0Fz
            eDd3L0JEalRiTXhCWVdnYzk3dTY2Uk95ZzA4CmJOK0pQbUJyaktrT0FITWUvTlFy
            K3dnL3NvWi9LWHVabW15c1NOQ0ZFSTQKLS0tIGV6MU5GbTBtK1F5dEErTVlRdUNz
            YzlxTUQydjFKK0QvMVVYYjFtdTA1ZTQKrzzwKkvBvtt53mrC98QXvufb55DrzlAO
            rQtKHSAGocpvIPBJK6nvpmnqoxzLGwZpZUiPI+MrdTrTE2Mkdmd0uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:02:29Z"
    mac: ENC[AES256_GCM,data:VkJGY3aM7GVO/WotqcZqbmC5xzNJ4XVQpn5uBXIYvAkk8xqDYMpq/FbuFb+djRQiFBDaiTboTVl8ZT930APHMkga6oCaHiYS46FXM5hbXz0gtJNkSuqcc7mZSMNBSQ1LnbULqJVzFSoHtg3S3Mi5iQawiWqpejTLLZ+icV/UIwU=,iv:W+mD5mMsJDNHY3uEoKKB7IzkTXOlp2W8s8cv8Hw5uqU=,tag:IhNsw/rhcSfdHXkWnyVuyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
