apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VY1pPL4lMJQM0wx8VhCpqAunqaWg4tRiUxp3dP7kbxxE88j104E0tw==,iv:0mu/R1u3+SurNaGs2ekd8CNWPzReY6xAaLQ7lI4UGsY=,tag:93mhXW47aXiZsGlSTkw+pg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdk4wWmNYVEl3YmVFaXQw
            MnNWdTV4ejV5UWdUVnJBdTYzb2xLaWYyRkdVClBHdzBLTWlKdlNDcm5lajE2YmVy
            VVVxLzFIb2hna2JmNVEzNi9YTUVHVHcKLS0tIFFHcXV3d2dOaTNidVNldVdCQlpJ
            V1lUWlVObS82a1h5M3dTTXJzM3FDcE0K2SU+Ro8qbjzkmwwDfs2+LFj62Ij4G1Xo
            LCzHS1MKGzdbNd2j9micbjTs/FUqktkOWEUL9wIhtZSDAxNOYZMnwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:42:00Z"
    mac: ENC[AES256_GCM,data:Zo/E/Mj3/NjP+sPtKVo3aGCj6ftLnscglN1cemAACTGsO/i8xfXNbplXYWd+n1x3QuIESkjTxWuzIIzjTd2iKY9a66N7uF7tl9P0jMB4NeSPNJCNxYGIuUOhuBJJ2Gk8Ofo59dUFQf6T8dNV/AhEfc69aTEWSNzBnglF8xnZ8dM=,iv:wsMV9fVgMgzfAm+SaISZGDCJyvFI4D+8ulQ8ECmZI8Q=,tag:JcC9PPB40pq+noIF6llv5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
