apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yh1Jlqnvi0ntmpklJTi+fhRIgQbwIXe6QzsRPP4qf6arwikE0GIH3A==,iv:u/8BPYngESBJogER3rdu9QgpGPIZfUCMNyKYnVpTvz0=,tag:CPxvOfXKhoMdq7GBgTmSJw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWlp5K0hLeFJSVlQ0VTlq
            L2I4ZFRtR0RpczJ1am12ODBKZlZrcDJhdnhzClNZc0dSaURXaFVRamFodStsbFBj
            YW1FNWFZOVFvc29RNDVjd0hTc1FvM3MKLS0tIDI1MlVaVDNaUlMrWEt5SzhaSDFJ
            TGhrUjVOeHFJTVlVMnNEZ1NvZmoxM0UKvlej9fsBHBCLSXBR4YUim7Pyk0iZ8Mke
            cz+nuAuQaYO0UXIG+uOrUJ5uoZz7okceGGTKz5n0Ywf5nQ2MCXi6CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:08:56Z"
    mac: ENC[AES256_GCM,data:AtRcxZg/kaExU5Yq6pKLlKtuCD5lIaP+bW8df9MgOWJkyheMdt5wpqFZNC86ANbbruKlFW6BfEjlJoPFvbnTl0iEPa8KZnlCXDvRgi8d3hbaCsdNdYoilw5TrD0dn/EAj/XdODLcWkOEAm9cvXeuGY/jr52pKdYSynKweHFjW/E=,iv:jmEDR1an3fV5U9O8jr/2573t5Eovv4xC0jrlWSRSkx0=,tag:q2E2uH4rJYkSmftc5cSV4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
