# ENCRYPT THIS FILE with: sops -e -i frigate-secret.sops.yaml
# Before encrypting, fill in real values for all fields marked <CHANGE_ME>
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: frigate
type: Opaque
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:fNtHMkxn,iv:0nZqouagn7b/ZHooKDu2aumMO5og16v/dG9LnPQ6ucw=,tag:vswTUrTRWmeVMfTjULEZGg==,type:str]
    #ENC[AES256_GCM,data:r3zSadQrVhADoBDJcglnNljTlu9Z3IcPlWjivxMYa6/tp/IbexFsn6MJBO+fQBCJFQzw2SudoCVfAEonqkgbRcVJ48CSkQ2imqiz,iv:7PtZHEsR5rl5KrgNQPzz/MEULCaMMG5yJyDjjstTI+s=,tag:3TuUksMIsIESt6HvDsofpA==,type:comment]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:wEB6V8yZk0wjCw==,iv:QOjj2IgPgHuQ4ZHISAIoqCNJari6uyNOj+LZMK4Qnjk=,tag:LWd28dQAaRqsGdb9Nb3shQ==,type:str]
    #ENC[AES256_GCM,data:4t4bTKFqonu61icbHb+4REIaKON2YofbSdkuBQnWb7HRGQ2i/O8DUuat+bW85gRs/GZcfG8LhsHqs1u7s+DGCKba7VaAPurfbM5u20dpH6A=,iv:v5pJzC9FBipYAz5bonYf2VMkwaIA2h1HJjXrRCJ5QtE=,tag:O7m1Wj1IbUH8vGuZBwB6cw==,type:comment]
    #ENC[AES256_GCM,data:tBVbCi9m+GokWTTm5Xataac06Q+0jtk+nie+riR8,iv:HuRqvV3x9v8IgbU1AHAVbL2KppL9rrEN7WNz7Fm9sxw=,tag:Zm3zGpCMufbkEiIb6Z+gSA==,type:comment]
    FRIGATE_ADMIN_PASSWORD: ENC[AES256_GCM,data:Da/YsLLL0lCobMK9LARQ/ldkbVw9a4JTVAvYsLdkopa8KSCS4n1SKA==,iv:PeV+X9phP1dM1Z3ioeiz8AGo27Qi49/ERCsxSBj5nfw=,tag:GvW0Ewp3yAr1PNk62Z5FOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWmdpODIrSU44NnpYOWxz
            WmZVK2sxeTJmSzVlMmJIZEFUSnpXeGNiN3pRCi9mS2JjTnNRUXl0UUI2YWNPNXJE
            aUFaN0ZicG9GUy9nNVdUWnl2ZTc4eFUKLS0tIEtEbWJ0QTVWdjkwQ0xNWWFDZGxV
            QW5lK0ZKVjdGeFRNTEZrMUVSZlh6cHcKLKV7wAeC4/viCYJ70KayBDKL+anjdnD8
            wPtLtyH//7O9SqlmIlOYSWqP1jZ1oReVbEE+Ww0uR+Aw8x7YptywwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T00:01:15Z"
    mac: ENC[AES256_GCM,data:y7Q/Z3mgXItZm9C5rE8TpWfOApBwd9vJ80dp4pd6dqyBC/bBwVtJxGeqLYj7PDn5ZXx3EveWRdimthGmxPVBGeCJFKXTZbeq04tadFLIrzDzYnKNzJTYqDOxmYKWhBIJXRPQvtpratZfByc4TsJpWEvmUbljB0IcvKaEvX0HeHc=,iv:w2fpnmPNvxHggPUqX6GrHdFJwr9TqiGzwnGVVdvjUo8=,tag:OII2nlmlZ7L9QAFtpt8kGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
