---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gsks1
  resources:
    requests:
      storage: 500Gi
