apiVersion: v1
kind: Secret
metadata:
    name: volsync-minio-secret
    namespace: pihole
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RLE7VQARQB/55th665bqiO/nKtBMT70sMxr2ioyDghLmHB+0/gljevX22G2fcd/o,iv:8jfVQaLnl3lxdD1FVC2ImeaLx0WCtU8AWsi/xoSsNRE=,tag:9D9Xk5UOE0EP6oMGR1W1fw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:XbKukoDIGs0b2mxkBAPdxg2OgZdlqJ0XkSkhIWQ+4JuUuZlbTGzhozvHMS4=,iv:J99axh/6FjmRmd3HHT3YyvAMJ2yc+Nb4Hc7qMTqaP10=,tag:hizfx3ZVIU3CDU3E/UKppQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uffXYv/nfA==,iv:Eh7/n4x2vrQnd0vYiILKR59KPHlqV3HTgLqdFWkhwzc=,tag:m5pFcMVEEC9ifkj2koNQ8g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HEPUdI20DQYWbQq9n1qzy/WOsBgT5MZcH3NBomqOMgnKl79AAwN9zA==,iv:4YfwFdqZDFhauIRuOpdn5IS6xwpxZoIJwWpOd6iBUxA=,tag:CzvDM5J7nKm/waNORLayHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OUtDcndSUkd6S242WjNF
            dVRxNjNmQmR2Uno3ZUsySk5kNUs1Y0l1M3cwCkU2Yy92eWdVM0hNakY4NE5rdmc3
            TlN5N0Nib0RCcEw2cWhWMU5NdWcrWmMKLS0tIExBS0U2RE1EV214ZUZsTk9iRVVR
            K1BQSE5sTnpwZFlKNEhOZ1hKcGgrSW8KWovuLcK6EwiWcI58cVZQu/HUW4uFEOtE
            PDMvjaAnBM19MyCMFR0Lb0LQffuaIFwXbJcByRGLAtdWcPE9wQWo6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T01:29:30Z"
    mac: ENC[AES256_GCM,data:5e0obDwAeNz87Q92VisYyErYs6mWIvKBQaKYnbKzJR3oNTT/vN355CGbno98f16J1QdgghLV91VbV6cn2AaXU8TQWS0s9nypF3mNk0FPYnnVGo5URfs59cMINmtIVXhrncKOwDKH45tafROcLY9BoLUNk3Oshj/IrQHZWIuUdsU=,iv:LcXhjxjWxCNQWD+/p3jQGhzImZRv1R/JjqcEXoWWIRU=,tag:/DGTeWKq9qXFBxMOSpuV4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
